### ISSUE TITLE
-4 kes unintended wall breaking?

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#100]
![image](https://user-images.githubusercontent.com/51264376/58752573-133d2c80-847f-11e9-94a4-3d64d4ff506b.png)

**Comment by jkachhad** [comment]
![image](https://user-images.githubusercontent.com/1934897/58819020-49a0b600-85fd-11e9-93dd-027d41d2b24e.png)

Good catch! The orange walls here were not tagged as indestructible. To do this without manually marking them all, they will be indestructible if the wall north or west is indestructible.

This alone seems to handle most cases:
![image](https://user-images.githubusercontent.com/1934897/58819167-9d130400-85fd-11e9-9ae1-2f7ee379ef8a.png)

There are certain pillars that are destructible, I'll create a third pass to identify those and mark them properly.
Thanks!
