### ISSUE TITLE
Nidhogg doesn't tether

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1002]
Vile Necro properly tethers.  However, after getting to Phase 2, I can confirm that Nidhogg does not tether and permanently galavants through the zone if let loose. [Reported by Vernak]

**Comment by Tawnos-LOK** [comment]
Can't help resolve this one myself.  Nidhogg isn't in the public segment file and in talking to Sewer, he doesn't really have a defined "Home" spawn area.

**Comment by Tawnos-LOK** [comment]
Resolved with implemented changes.
