### ISSUE TITLE
Level 24 adds for Knight added no AR

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1025]
No AR increase from the +1 str/dex add at 24 for Knight. [Reported by Zathras]

**Comment by Leolus** [comment]
![image](https://user-images.githubusercontent.com/7170292/140243042-8560f88c-9222-43ee-a233-7874e507bd71.png)

**Comment by Leolus** [comment]
![image](https://user-images.githubusercontent.com/7170292/143670471-a8b2c855-b24d-403c-9b58-57eced870168.png)
Can be closed as working as intended

**Comment by Tawnos-LOK** [comment]
Closing as per Leo's note above
