### ISSUE TITLE
clicking feet (movement)

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#103]
clicking feet should allow you to completely remove the feet effect, single clicking feet to avoid blown walls, etc and not use autopathing can be challenging.

**Comment by SlysterLOK** [comment]
Right click clears the path

**Comment by mtweldon** [comment]
ahh ok

**Comment by jkachhad** [comment]
At some point I'll have to refactor some of the map interactions. You can get rid of the last step by clicking the step prior. On the next patch, clicking on the center tile will clear the path.
