### ISSUE TITLE
Axe UD - Visual changes to no recall area

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1031]
Since the no recall area was expanded farther north above Vile Necro, there isn't anything that telegraphs to a player that they are approaching a boss area.  Working on a floor tile suggestion to Sewer & Lux for better visual conveyance. [Suggested by Vernak]

**Comment by Chilly021** [comment]
This was all changed with a newer change to Axe UD. You can almost recall anywhere now. (except lair)
