### ISSUE TITLE
WorldForge - Drag & Drop to tile an area

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1035]
Quality of Life addition to make designing regions more efficient, while cutting down on human error from missclicks. [Suggested by Vernak]

**Comment by yarrim** [comment]
Vaguely resolved in #1040.
The Paint tool and\or copy\paste has the correct workflow to cover a large area with a component.
If covering an area with a default component, select the area first, then the paint tool, then the component, then click in the selection. Floor-type tiles will be overwritten by a new floor (floor, ice, water, sky), other components will be appended to the tile by default.
If covering an area with a custom component with a hue or other metadata, select the desired tile and Copy with Ctrl-C, then select the destination area and paste. If the target selection is larger than 1x1 tile, the clipboard will be tiled to cover the area. This overwrites existing components in the target selection. Ctrl-V only applies to the first selection rectangle if multiples are provided.

**Comment by Tawnos-LOK** [comment]
Closing issue.  After edification, more of this functionality exists than I was aware of at the time.  Thanks, Kora.
