### ISSUE TITLE
Bloodlands; Knight STR Quest completing early (maybe?)

### ISSUE THREAD

**Issue by rutir** [jkachhad/Stormhalter#1036]
I did 'teach me' at restel, killed flordex, then 'teach me', he requested the necro kill. I then poked around but never quite got to necro, and certainly did not get the kill. For a break I killed unicorn, changed facets from pearl to ruby, then teach me at restel just to re-read what he had said, but instead he gave me point. Not sure exactly what caused the trigger, maybe unicorn kill, maybe I had some flag already, I'm not sure. I'm 99% sure I've never been near the necro lair, or the caves at all since shortly after it was first put in.

**Comment by Tawnos-LOK** [comment]
Resolved in Leo's update
