### ISSUE TITLE
HP regen

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#104]
it no worky

**Comment by jkachhad** [comment]
I'll need more details, seems to work just fine after "kill" and "resurrect." In what situation did this occur?

**Comment by zrikzlok** [comment]
hmm I'll have to test more. I may have cast fire/ice on myself and I tabbed out and back in, after about 10 minutes and still had the same hps I was at when I tabbed out. Perhaps after combat? Will check later to try and reproduce
