### ISSUE TITLE
Creature List Movement

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1046]
Creature list becomes unusable when there are more than a page or two of creatures on screen. It jumps around and reorders multiple times a round even if nothing moves on the screen. [Reported by Zathras]

**Comment by jkachhad** [comment]
The list is meant to be ordered by distance from the center tile. Not sure how to make this stable if entities are moving often. It's a problem due to just high speed on the facets.   Should we just place 1 entity at the top that is the lowest health?

**Comment by sproatba** [comment]
the order by distance part seems to be fine, but the list should keep a consistent order for the mobs at the same distance.  It seems like one new group jumps on screen triggers a full order refresh or something.  Not sure if there is some variable that it sorts by other than distance, but some sort of order it came on screen would be ideal.  Maybe how long it's been alive, or a spawn id or something?

**Comment by sproatba** [comment]
This is the old one, I was going through cleaning things up and commenting when I could.
