### ISSUE TITLE
Tethered NPCs with Location Spawners don't wander

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1054]
NPCs with location spawners that had a wandering AI like peacekeepers or bosses used to wander within their physical range or Entity.Home boundary. If the entity is IsTethered=true, they no longer wander, though will still move outside their spawn tile to attack. They then seem to wander freely inside their Home until the tether logic forces them back to their spawn or maybe until they naturally land on it. This obviously impacts Town Peacekeepers, but also affects some enemies and bosses that use location Spawners and an arena. [Reported by korazail]

**Comment by yarrim** [comment]
A quick scan shows this affects:
Doom.Orc and retinue,
Oak Serpent
Pescalanor
multiple Grove mobs (if they were supposed to move)
Elder.troll, his troll guards and crypt guardians
Several Bloodlands bosses
and a large swath of friendly NPCs.

**Comment by yarrim** [comment]
Initial assumption was incorrect: The isTethered is irrelevant. I haven't wandered down into the Serpent Sea to validate Serpent and Pescalanor, but Doom.Orc and his allies just stand there unmoving, but only Doom.Orc himself is tethered. Elder.Troll and his guardians are also immobile, but only the boss is flagged as tethered.

**Comment by jkachhad** [comment]
Resolved on v0.85
