### ISSUE TITLE
princess - odd behavior

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1055]
When princess comes down the eastern troll king steps into -300, she loses "follow" every time and I have to command her again.  On every other set of steps on the way to town, she automatically follows me past the steps without an additional command.  Something seems different about the eastern steps of the troll king palace, shes lost follow on those steps 3/3 times in 3 runs. [Report by XeroX]

**Comment by Chilly021** [comment]
Original issue fixed.
