### ISSUE TITLE
Spell effects cannot be refreshed

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1070]
When recasting a buff (Speed specifically, though Featherfall is also affected, so probably all buffs), the duration is not reset. I can cast Speed while I still have it active and have it wear off a few rounds later. As a player, this is unpleasant, so I doubt this is desired behavior. I also think I was refreshing spells like NightVision in a previous build without issue. If this is desired behavior, then the spell should fizzle to imply it didn't do anything and there needs to be a way to intentionally remove a buff before it expires. [Reported by korazail]

**Comment by jkachhad** [comment]
Should be resolved in the next patch. Good catch.
