### ISSUE TITLE
Can we not move spells around?

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1076]
In original LOK (I get this is not original, so apologies for that right off the bat lol), there was a little spell book you could open with all your spells (purchased) in it. Then, you could move them around in your spell pallet however you want.

Any plan to implement this? [Report by NotTaelamar]

**Comment by Chilly021** [comment]
![image](https://user-images.githubusercontent.com/90510109/206716768-b5619ae6-3341-4b0a-b2cd-304e1aecc07c.png)

when implemented we can re-address this to see if it meets the concerns.
