### ISSUE TITLE
Pathfinding issue in melee AI

### ISSUE THREAD

**Issue by yarrim** [jkachhad/Stormhalter#1081]
Ref #759

I can recreate the behavior consistently by doing the following:
drop into Hob caves and portal\break the wall just above the water hex:

If a *melee* mob can see a player standing in either water hex, then they will not move. Ranged and caster mobs don't care and will wander off. Once the melee mob loses sight of the player (casting darkness on the hex, or moving a hidden thief off it), the natural wander AI will take over and walk them off the hex.

Breaking the wall just E of the top water hex open another diagonal escape from this hex, but mobs stay trapped. Blowing the wall E of the trapped hex will release mobs.
![image](https://user-images.githubusercontent.com/11442233/142212732-7467f95a-2844-47c6-81ba-03e1458d72ee.png)

My guess is that the melee pursue AI gets stuck if there are no places to move in the cardinal directions.

I've been unable to find other suitable hexes to test this, though, and couldn't get anyone in oak -2 to fall for a hand-made one with illusions.

**Comment by yarrim** [comment]
Got it to work with a bonfire, though:
![image](https://user-images.githubusercontent.com/11442233/142214439-0114a29a-77ab-4dc3-bf2d-93a4c342f5f2.png)

That mob isn't moving. It can see me in the water hex, but the only valid directions it can move are diagonal.

**Comment by jkachhad** [comment]
I've identified where in the code this issue occurs. The question is, what should be the behavior when an AI can not reach the player? Should it randomly select a path-able tile and move to it?

**Comment by yarrim** [comment]
As a player, it is certainly nice for the mobs to stand still so I can shoot them and their loot isn't scattered everywhere. I vaguely remember mobs that could not reach me in the puddles just standing there glaring at me in GameStorm days, but I was a kid back then.
At the moment, there is a difference of pursue behavior based on the availability of an open tile in a cardinal direction. If they can see a player but not reach, and they have an open tile in a cardinal direction, then they will randomly move, including wandering off-screen. Standing in the southern pool, mobs will enter the screen, see my wiz and continue to path around instead of locking up. Only if they end up in a place where they have no cardinal direction to move will they stop wandering. The hob in my second screenshot could path away NE or SE, but will not do so until the bonfire expires, opening the E tile.
If I stand in the hex between the two pools, with only the one wall being broken like in the second screenshot, I can lure a whole zoo onto that hex, then step N or S into safety and plink away. Again, it's not like this area lacks for density, so I'm not gaining much except that the corpses are all on one tile and easier to loot.

To answer the question, I would say yes: a mob that cannot reach the player should pick a random path-able tile to wander to. In most cases right now, this is what happens. It'd be nice as a player if they would hang around, restricting their random paths to ones that keep the player in view.

**Comment by jkachhad** [comment]
Thanks for the feedback, I'll likely do something in between. When the entity is <= 1 tile away, it will move 1 tile in a random direction that is path-able. Once it moves > 1 tile away, it will randomly wander away. This will give players a single opportunity to interact with the creature before it moves away.
