### ISSUE TITLE
youth potion drop rate

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1083]
Currently youth potions are way off.  They are the ONLY stat potion currently with perpetual usage [ie: you always need them], but the current drop rates are extremely wonky.  I have spent maybe 6 hours the last few days hunting undead UK, which I otherwise never hunted.  Until now, I've been in desperate need of stat potions, basically always having zero of them available and constantly needing to find one whenever I age.  After hunting UK UD for maybe 10 million exp at level 20 [so, not a long time], I now have 12 youth potions lockered and have drank 2, so I've gotten at least 14 in the last two days.  Solution to this is two fold:  1)  lower the drop rate of youth potions in UK UD, it is currently way too high, dropping approximately 1% of the time by my guess.  2)  add youth potions to 'normal' stat potion loot tables so that they can drop the same percentage of the time as other stat potions, which would offset the need for zones like UK UD to hold a monopoly on them, which most people cant hunt until the end game [Suggested by Smitty]

**Comment by Tawnos-LOK** [comment]
Closing this issue for now.  There have been YP adjustments to UK in patched changes as well as YP drop rates in other lands.  This likely won't be the last of that tuning but I believe the core of this issue has been addressed.
