### ISSUE TITLE
training past level experience

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1101]
If you train past experience where you would ding, It does not ding. Last time it happened, I killed one mob and dinged with HP increase etc. This time I trained while level 13 and passed exp needed for 14 and it did not ding and add HP, mana etc. I went back on the replay and it shows the number level increased but no HP or mana increase. See screen Shots. (I am 14 with 13 mana/HP/stamina at this point) [Reported by Chesterwiz]

**Comment by Chilly021** [comment]
We can re-open this, but we have not seen this recently. Please report if you see this again.
