### ISSUE TITLE
balms at priests

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1103]
I think it’s past time for balm sellers to be nearby the priests. But even that may not solve the issue if you die/release and have no coins, unless there’s balms left on the ground. Either way, I really don’t think you should die and be punished for the death, be punished by having to get your loot back, AND be punished by having to walk 1 hex all over town to get gold or balms or whatever… it’s just a quality of life thing. When you die you shouldn’t require 100 clicks to restore your health. [Suggested by Smitty]

**Comment by yarrim** [comment]
Another solution might be to spawn in with 2 stamina, so you can run. Maybe 3 if that's required for sprinting.

**Comment by sproatba** [comment]
OG you spawned at half health with 1 stamina so you could immediately run around, it was only an issue if you didn't get looted and were heavy and lost stamina when moving.  Lands was more brutal.
