### ISSUE TITLE
Tile-targeted instant spells cannot be cast-with-path from command line

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1104]
Shadowstep is the only one I'm familiar with, but there may eventually be others. I can cast a normal spell, like darkness or bonfire by command line with 'cast e e e'. Since I can't warm Shadowstep, this doesn't appear to work. Attempting to cast shadowstep to a specific hex via command results in a targeting cursor. I can 'cast shadowstep' and then double click to confirm a target, but not 'cast shadowstep e e e'. [Reported by korazail]

**Comment by jkachhad** [comment]
Fixed on next update.
