### ISSUE TITLE
Lockable Hot Keys

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1131]
Make hot keys lockable / unlockable so that you can edit as needed and lock it in when fighting so you don't accidentally drag the spell you want to cast off of your hot key. [Suggested by Drizi]

**Comment by yarrim** [comment]
Solving the same problem as #782. Sometimes, a double-click-to-cast is interpreted as a drag and instead removes the spell from the hotbar.

**Comment by Tawnos-LOK** [comment]
Merging with #782
