### ISSUE TITLE
mob wander behavior - issue

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1143]
after the last few updates [maybe the tethering one specifically], I am noticing mobs are way more segmented and don’t seem to naturally wander around the way they should. There are numerous areas where I run through 3 screens of tiles trying to find mobs, then I’ll stumble onto a hex where 4 packs of mobs are “stuck” and just moving back and forth in 1-2 hexes. I’ve noticed this on multiple levels in axe glacier and kesmai. The oak portal in -4 kesmai has 1-2 mobs typically, opposed to historically being very crowded. It just feels very “off” at the moment. [Reported by Smitty]

**Comment by yarrim** [comment]
Probably related to #798.
