### ISSUE TITLE
Items disappear sometimes when mobs loot a player

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#115]
I had a few items disappear when a troll and goblin killed me and they looted me.

**Comment by jkachhad** [comment]
I imagine you checked by killing the troll and the goblin? 

There was an issue where killing the troll/goblin would effectively "delete" it and remove it from the map, but deleting the creature also deleted the items it was carrying. This should ideally only happen for player characters. It's been fixed for the next patch.

**Comment by SlysterLOK** [comment]
Yep! The only thing left was the wing helmet and 1 strength ring. Thanks!
