### ISSUE TITLE
Client crashing on Knight - Oak TT

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1154]
I've had a client crash on my knight while hunting Oak TT about 4-5 times in the past day.  It just happened again so heres the most recent Replay.  I don't recall this happening before Oak TT, but thats where I moved to once I got my hummer sword.  I am not sure if its specific to Oak TT or maybe related to the speed of the actions while using a hummer sword. [Reported by Smitty]

**Comment by yarrim** [comment]
[random_disconnect_on_Knight.zip](https://github.com/jkachhad/Stormhalter/files/7657111/random_disconnect_on_Knight.zip)
Copy of the replay from Discord.

I checked out the ending of the replay, and the description Xero had in #docks of this issue doesn't match the end, so this may not have any useful data.

The issue as reported on #docks:
Xero: So I’ve had a weird client crash instance that has caused me to die 3-4 times in the last day. It only occurs on my knight, no other class. I think it may have to do with the speed commands are trying to be executed… like if I’m spamming the * button to attack, then switch to quickly trying to execute “cc” to heal myself, then switching to quickly trying to recall. I think maybe all the clicking and pressing ENTER at the same time is overloading something.

**Comment by yarrim** [comment]
[Another_disconnect_-_Knight_Oak_TT.zip](https://github.com/jkachhad/Stormhalter/files/7663300/Another_disconnect_-_Knight_Oak_TT.zip)

Another example.  Xero states that the replay ended on the same pack of mobs as when he crashed, but may not have the last swings. He was not trying to issue multiple commands, other than mashing *.

**Comment by yarrim** [comment]
Xero: Just happened again in Axe so its not zone specific.  This time it happened while i was trying to Raxe 3 mobs.  I was pressing "up" on the keyboard to cycle to the last command, then i was holding the ENTER key to spam the ranged attack whenever the timer subsides
Xero: Crash happened while I had a timer and was spamming the next throw command

**Comment by Chilly021** [comment]
Please let us know if this is still happening. Thanks. Closing temporarily due to staleness.
