### ISSUE TITLE
safe hex in TK lair for vamp thieves

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1155]
there is a safe row in TK lair where the elite guards cannot see you, and where TK also cannot see you, if you’re a hidden thief with a vamp cloak. The cloak already provides enough benefit that full immunity from any threat should probably not be a thing, or should be very very rare. It is the 3 hexes in TK lair where the 3 doors are located. No mobs will walk into those door hexes, therefore cannot see a vamp thief. Extending one spawn region or the other to include the 3 door hexes seems like it should fix the problem. [Reported by Smitty]

**Comment by jkachhad** [comment]
Fixed for next restart on 12/13/2021
