### ISSUE TITLE
Spell Proc Weapons

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1156]
when a user does damage with a weapon, the magical weapon has a chance of casting a direct damage spell. Whether it's death, curse, magic missile, lightning ie Thor's hammer, or ice spear, it would be nice to see this added similar to lands. [Suggested by Chillz]

**Comment by Chilly021** [comment]
This was taken care of with Sewers land addition. THOUGH! it was taken away at the weapon level and used on the item level. We could probably address that for opinions? 

@Tawnos-LOK @Leolus
