### ISSUE TITLE
make shopkeepers and bankers the same

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1162]
just seems like an easy way to cut down on ridiculous clicking. Why not be able to sell your gems and then be able to deposit your money without picking up the money from the counter?  We would still love an easier way to get it to the trainers, but if it’s possible to combine shopkeepers and bankers into one, I don’t know why you wouldn’t, from a practical perspective. [Suggested by Smitty]

**Comment by Chilly021** [comment]
This is a legacy artifact and not likely to change.
