### ISSUE TITLE
anti recall functionality

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1163]
currently there are anti recall zones where you cannot remove a recall ring.  One thing I found that may be an oversight is that you can SET a recall ring in an anti recall zone and recall to the zone at a later time.  This seems like something that should work both ways to prevent abuse in boss lairs. [Reported by Smitty]

**Comment by jkachhad** [comment]
I tested this in Daisy's lair and was unable to reproduce it. Where exactly were you that this issue was occurring?

**Comment by bsmittyau7** [comment]
Brickland in the pit with the evil crocodiles

**Comment by Chilly021** [comment]
Working as designed, thank you!
