### ISSUE TITLE
game freezing in axe

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1165]
, in the south west side of the skull caverns near the rope to lockpick. Twice in twelve hours there was lag followed by freezing when I entered the area. I couldn't move, I couldn't balm, and then died (both times). Outside the area it's fine. [Reported by stardust]

**Comment by Tawnos-LOK** [comment]
Spoke w/ Star.  Believed to be an isolated incident with lag at the time.
