### ISSUE TITLE
Thaum spell fizzle

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1166]
one of my favorite things about being a Thaum in Lands of Kes was basically being a warrior-priest that used my djinns to supplement my hand skill. I feel that is a little lacking here, especially on Opal, due to the fragility of djinns and the low hp of Thaums. I see that Turn Undead appears to add your missing hp to the damage and returns something like 1 mana per enemy killed. This would seem to favor a gameplay of holding turn undead until the perfect moment, but since death spells and magic missiles interrupt spells so easily, I would like to propose a buff or class feature that makes thaums resistant to being interrupted while casting [Suggested by Mersyl]

**Comment by Chilly021** [comment]
Moved to consolidation thread. 

https://github.com/jkachhad/Stormhalter/issues/1216
