### ISSUE TITLE
thief magic training accessibility

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1167]
thieves guilds need their own banks. Once you’re high enough level, there is not much of a way to train thief magic without recalling 130k at a time specifically to the trainer over and over again. Other classes can at least push gold.  Thieves can push gold in UK, but in other zones the thief portals stop the gold from making it all the way to the trainer. Any zones that were once accessible can not longer train me because I’ve outleveled the trainer. It just shouldn’t be this big of a chore to train on your class. [Reported by Smitty]

**Comment by jkachhad** [comment]
New rings added to add some meta to hunting and gold carrying.
