### ISSUE TITLE
show training command

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1168]
this command either gives a bad answer or else training is not strictly linear.  at 1% if you max train (50%) it shows as training 58% ahead, where in the last portion of the level each percent shows as costing more than the lands chart. I believe it is an issue with the show training command giving inaccurate data, at least at skill 16-18. [Reported by Olorin]

**Comment by jkachhad** [comment]
It's not linear as the log scale here pushes your half-way mark actually past 50%
