### ISSUE TITLE
Win11 - Auto HDR

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1177]
I have the game running on Windows 11 with Auto HDR turned on.  Sometimes, when people watch my stream, the brightness and color saturation increases dramatically.  My educated guess is that it is just Auto HDR not knowing how to handle the game.  I don't think it is a true game issue, per se, but wanted to make a note of it.  I might try seeing if you can make exceptions for Auto HDR settings [Reported by Vernak]

**Comment by Tawnos-LOK** [comment]
Not inherently a Stormhalter issue.  I was able to resolve independently and will share that info in a community doc.
