### ISSUE TITLE
idle kick

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1198]
if there’s not a good reason to leave it the way it is, might I suggest a 1 hour idle kick to conference for an idle player who stays logged into the game but has performed no action. Just standing still for an extended period does nothing except age your player in the event you accidentally stayed logged in, and it can also cause a player to be locked out if they accidentally stay logged in at work or home if they play at both locations. Very low urgency but I feel like this would be a good addition. [Suggested by Smitty]

**Comment by bsmittyau7** [comment]
I mistyped… a kick to conference wouldn’t resolve the issue of being logged in at another location. I meant to say kick to login.

**Comment by jkachhad** [comment]
On next update, clients are disconnected from the world after 10 minutes, and from the conference after 15m.
