### ISSUE TITLE
Client connection test is a DDoS

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1204]
Apparently, the game has a hard connection cap now that makes a DDoS with bullshit accounts very vulnerable.  I'm assuming this was put in place when the game created 400+ phantom sessions that one day.  In any event, might want to revisit where appropriate [Reported by Vernak]

**Comment by Tawnos-LOK** [comment]
As Lux mentioned in discussion, the session cap seemed to get introduced / changed when the Lidgren library was updated to a new version.  Lux mentioned this was adjusted on a reset.
