### ISSUE TITLE
illusions should be temporary and limited

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1215]
Illusions should be temporary distractions on the enemies.Currently players can terraform entire lands.. A newbie could be killed this way.Maybe Max amount of illusions per player and a short spell duration of 1-3 minutes. [Suggested by Midgit]

**Comment by Tawnos-LOK** [comment]
The current maximum chance of any mob believing an illusion is 36% and is rolled per mob / pack and rerolled on pack splits or stuns.  1-3 minutes would be that pendulum swinging very, very far in the other direction.  That said, the current duration is somewhere between 10-12 hours on Opal, I've estimated.  I think we can unanimously agree that is pretty bonkers.

**Comment by jkachhad** [comment]
We could change spell timers based on where they are cast. If cast in town, we can reduce down to 10% of the duration.

**Comment by jkachhad** [comment]
Illusions will last for 5% of their original duration when cast in town.
