### ISSUE TITLE
Resolution support

### ISSUE THREAD

**Issue by mtweldon** [jkachhad/Stormhalter#122]
Allow the changing / stretching of the player screen resolution, even if it will distort, we shall accept the consequences ;p

**Comment by jkachhad** [comment]
I threw some code together to test how difficult it would be to get the game into different resolutions. I was able to get the sprites to stretch without distortion. I will have to rewrite some render and input logic to support the stretched sizes. I did notice that input did not always match where the button/sprite was, so likely hitting some kind of precision issue. 

Will keep working on it.

**Comment by jkachhad** [comment]
This should be resolved, let me know if you have further issues with resolutions.
