### ISSUE TITLE
WF:Push tiles

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1220]
a directional teleport push tile. This can create slides that push the players around a map.A rushing river. A windy peak. a shifty maze. [Suggested by Midgit]

**Comment by yarrim** [comment]
I thought SewerCzar or I had created a 'scriptComponent' suggestion ages ago, but I can't find it to link here.
The generic version of a push tile would be a tile that would run an arbitrary function, from the server or segment code, on the entity stepping on it. This could be used to simulate currents in water or wind by moving players and entities on them or to make traps like the concussion hallway before OL.

**Comment by Chilly021** [comment]
Duplicate. As mentioned above.
