### ISSUE TITLE
equipment visuals

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#127]
Visuals for when you equip equipment aren't being displayed on your portrait. .

**Comment by jkachhad** [comment]
This is intended. As a way to introduce different items with new graphics, we'll have to avoid using portrait art. Each piece of equipment requires an 16 additional art pieces also to be drawn by an artist (8 nationalities x 2 genders). If the art is a bracer, 32 frames. I want to be able to commission new art, but the portrait sprites would add significant cost.
