### ISSUE TITLE
Lower Skill Training

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1274]
Skill training needs to be decreased to accommodate current economy implementation [Suggested by Chillz]

**Comment by SewerCzar** [comment]
I don't believe gold is dropping less than before in any significant way. Gold amounts were entirely made up prior.

**Comment by Chilly021** [comment]
"I would rather see a reduction of training costs rather than increased income...mainly because moving gold is a giant headache"  - Healthy Snack. 

The above item was reported by Healthy Snack.

**Comment by jkachhad** [comment]
Resolved with new ring additions for quality of life improvements.

**Comment by SewerCzar** [comment]
> Resolved with new ring additions for quality of life improvements.

Aren't we worried that players will just never leave hunting grounds sitting there indefinitely translating gems into gold and if they die retrieve the ring and never risk any of their gold? Essentially solidifying the "stand in one spot forever" meta that's becoming the servers go to?

Also takes away almost all risk of losing gold on hardcore.

I'm really not sure the implications of these rings have been thought through.
