### ISSUE TITLE
more defense on lower staff weapons

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1284]
OL staff is a clear choice for endgame casters but the previous two staves are bad. The first one is bad offensively and defensively, and the next is bad defensively. Wizards in particular need more defense to stand w mobs and AOE, so they’re using swords instead. Better staff options would resolve this. [Suggested by Smitty]

**Comment by sproatba** [comment]
@Chilly021  can be closed

**Comment by Chilly021** [comment]
Added and fixed.
