### ISSUE TITLE
orc casting web 3x in a row

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1286]
in -3 kesmai the orc caster just casted create web at me 3x in a row without ever using MM to deal damage. Did not seem like a good use of mana, seems like an AI issue [Reported by Smitty]

**Comment by dedmist** [comment]
So the way this is coded is to create an attack collection, then each items is a random chance.
If we were to fix this, there should be a progressive state AI:
Creature has an in battle flag state that starts when they see a player and stops 1 turn after the player has left their sight.
The battle flag flips to 1 upon seeing a player
1 -> Creature Attack Collection( next action flag = 2)
2-> Creature Attack Collection( next action flag =2 or 3)
3-> creature attack collection ( next action 3)
on lost sight action flag resets to 0 - general AI

**Comment by Chilly021** [comment]
This was due to the % of attack. Someone just needs to re-evaluate the spell cast. We should be good here.
