### ISSUE TITLE
The BBS

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#129]
I cannot for the life of me wield this weapon. It keeps leaping out of my hands! And Ironbar as far as I can tell cannot yet craft the BBS to test that one.

**Comment by jkachhad** [comment]
[Luxxx 2019-06-06 12-34-24.zip](https://github.com/jkachhad/Stormhalter/files/3262570/Luxxx.2019-06-06.12-34-24.zip)
Worked without an issue on this replay. Are you that the BBS was from that character? Trying grabbing another one.

For Ironbar, try using "ironbar, craft broadsword" -- It's not a traditional directive, I'm not sure how we can help new players learn them. Perhaps having ironbar tell the player to ask him to craft a weapon type.

Alternatively, we could consider adding context menus to the NPCs. When clicked, the menu would show possible actions that the client can take (craft, sell, buy, follow, begone, etc.)

**Comment by SlysterLOK** [comment]
I have tried several different ones from the Treasure NPC. I will grab a replay of it.

**Comment by BadAmp** [comment]
On your thief?  Isn't BBS a lawful tied weapon?   Or is it not yet?

**Comment by SlysterLOK** [comment]
On Fighter / Knight. Turns out it is because it is strictly a two handed weapon right now. Carrying a returning weapon caused the issue.
