### ISSUE TITLE
crocodile on kesmai surface worth too little exp

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1301]
the crocodile was very difficult to kill (right upstairs from -1 kesmai) and was only worth 400 exp.  the mobs in -1 kesmai are worth the same exp but much easier. [Report by Hardcore.Parkour]

**Comment by dedmist** [comment]
This has always been the case for surface creatures in all iterations of Kesmai.  They're not proportional to Exp near the leng town or out in the Kesmai forest either.  BUT, they're not really much of a hunting ground, there just aren't enough of the creatures; and more would cause town problems.  They're more ambiance and for the occasional portal gem or wb boots.  Unless there's a bunch of support for this, I'm inclined to let it stay.
