### ISSUE TITLE
crash related to coin/sack movement

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1308]
for the last two days or so I have seen a very consistent crash instance that happens frequently when you try to drag/split coins from your sack to the ground, or from the ground to your sack. Seems to happen randomly, but a large portion of the time. [Reported by Smitty]

**Comment by jkachhad** [comment]
Any replays of this occurring?  If I playback the replay, it should recreate the crash.

**Comment by jkachhad** [comment]
Identified the issue. I'll put a patch in tonight to resolve it.

**Comment by jkachhad** [comment]
Resolved in the next update
