### ISSUE TITLE
MA JK Still being blocked above average

### ISSUE THREAD

**Issue by Leolus** [jkachhad/Stormhalter#1311]
See Jumpkick vs melee attack chances to hit. 4th dan at 50% vs 20 base dodge.

![image](https://user-images.githubusercontent.com/7170292/153102915-0e821279-6b0e-4904-a285-f5cc14e67397.png)

**Comment by jkachhad** [comment]
Next patch should adjust the AR to be higher as you don't suffer -100 innate penalty from encumbrance, even if 0.  Base attack power now also includes dexterity and skill, rather than just skill alone, similar to melee swings.
