### ISSUE TITLE
lightning on water

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#133]
Not sure if it should be removed.. or perhaps double the damage since it is a good conductor? if you cast lightning while in water you should also sustain damage of some sort / and or be stunned?

**Comment by SlysterLOK** [comment]
I remember if you casted Lightning while IN water the lightning bolt would hit you. You could not cast from land to in water or over water. I would be ok to be able to cast from Land to In water.

**Comment by jkachhad** [comment]
I've gone ahead and implemented the behavior as described by Slyster. Lightning Bolt can not be cast from land to water, or over water. If casting from water, you will strike your own hex.
