### ISSUE TITLE
populate -1 Kesmai more

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1334]
there's not enough crits down there for a dock baby to get any kind of skill from, which forces them into -2 which may be too much for a dock baby [Suggested by stardust]

**Comment by Wirednuke** [comment]
This is because the mobs spawn in the secret rooms, and Lux is addressing this fix.

**Comment by starfire5** [comment]
Perhaps faster respawn time in these areas?

**Comment by dedmist** [comment]
Lux wrote some spawn fixes, about how long does it take now?
I know a few people in Jade have been down there a ton, maybe they have some input on respawn time.  If I made a change I would do it away from the stairs and not in the whole zone, the stairs are generally pretty good.

**Comment by starfire5** [comment]
> Lux wrote some spawn fixes, about how long does it take now?
> I know a few people in Jade have been down there a ton, maybe they have some input on respawn time.  If I made a change I would do it away from the stairs and not in the whole zone, the stairs are generally pretty good.

I haven't spent any time down there recently, not a dock baby anymore, but I can to note the times. I think the stairs are good as well because they can be near the temple if they need a safe place to go for help. Hopefully people will want to venture out and not just default to -2.
