### ISSUE TITLE
longer buff times on fire/ice protection spells

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1338]
[Suggested by stardust]

**Comment by Wirednuke** [comment]
See my suggestion on Issue #1351

**Comment by starfire5** [comment]
The fire/ice protection spells are useless with such a short buff time. A caster would spend more time continuously casting those spells to protect someone than the time a buff actually lasts.

**Comment by jkachhad** [comment]
```
Duration of all Resistance and Protection spells have been doubled.
```

Not sure if this an issue anymore. Closing. Can create new issue if still not properly tuned.
