### ISSUE TITLE
cursor window priority when splitting coins

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1352]
previously, whenever you go to split coins and the text box appears for you to type how many coins you want to split, the cursor priority always defaulted to the text box so that you could start typing the coin amount without having to click inside the text box. Now, you can’t type the amount of coins you want to split without actually clicking inside the text box again after you split the coins [Reported by Smitty]

**Comment by jkachhad** [comment]
No issues with typing the number soon as the window is open.
