### ISSUE TITLE
Throwing Rdagger from belt

### ISSUE THREAD

**Issue by BadAmp** [jkachhad/Stormhalter#136]
When the Rdagger is thrown from belt....in other LOK worlds it would either return to right hand...or if right hand taken drop to ground....

**Comment by SlysterLOK** [comment]
IMO I would like for it to return to belt if thrown from belt lol :

**Comment by BadAmp** [comment]
HAH I agree it is quite handy..just not the way OG was...

**Comment by jkachhad** [comment]
When thrown from the belt, daggers will now return to your free hand.
