### ISSUE TITLE
sorting it crit list/default target

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1365]
currently targeting defaults to the mob who most recently moved to your hex. There are benefits and drawbacks to that, some people like it while others may not.  I suggest adding a way via settings, if possible, to change the default targeting to the oldest mob in your hex rather than the most recent. This in particular can assist wizards who AOE mobs in their hex to weaken them before killing them, but then other mobs rush in while you’re attacking the weaker mobs, allowing the weak ones to heal while you attack the new mobs that just arrived.  I would not want to change or take away the old sorting method, but add an option for the player to choose either [Suggested by Smitty]

**Comment by dedmist** [comment]
NG targets by last hit followed by oldest seen.  Anything that goes offscreen becomes untracked.

So, if you get a runner to severe, then they dance around in an enclosed space, always within line of sight, if you have 4 unhit mobs on your hex and the runner makes it back to your hex then they get the next hit.

I expect that this is implemented with a queue and a stack on the client side, a mob queue that's in the order of mob seen and a hit stack that preserves the last hit mob.  Loss of LOS removes from both.
