### ISSUE TITLE
Spells are too easy to remove from the spell bar

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1376]
Sometimes during vigorous double clicking if there's even a slight movement the spell will move off the spell bar instead of be clicked.  It would be nice to require a larger distance of travel for removal.  This also applies to searching corpses, could end up with a moved corpse instead of a searched corpse. [Suggested by Asheron]

**Comment by trlook** [comment]
This or a locking toggle.

**Comment by Chilly021** [comment]
Locking was applied. Closing this.
