### ISSUE TITLE
RHammer Locations

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#138]
On the Altar in Ydnacs lair and behind Daisys lair on the ground in the corner. Probably not reached this point yet so no worries.

**Comment by jkachhad** [comment]
The hammer should be part of Ydnac's loot and one of the ghouls behind Daisy. The issue with leaving treasure laying around would be players just running in, grabbing it, and running off. Then the next person coming through would not be rewarded.

In the OG, they were only available just after a reset.

**Comment by SlysterLOK** [comment]
Fair enough!
