### ISSUE TITLE
Expose OnEquip() implementation

### ISSUE THREAD

**Issue by trlook** [jkachhad/Stormhalter#1392]
The code for lightning resist on the lightning shield is exactly the same as the lightning ring, yet it doesn't get applied. This implies there is some difference between shields and rings being checked for OnEquip() (and possibly other items like weapons)

**Comment by tlook19** [comment]
Per discussions with Lux, might need to implement an OnWield method. Can someone flag this high priority?

**Comment by trlook** [comment]
seems fixed now?
