### ISSUE TITLE
axe level - out of sync with progression

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1415]
the dungeon level between lockpick and axe UD seems very out of place as far as progression. It is easier than the lockpick level, and worth less exp and gold. It doesn’t make much sense to have to fight thru a dungeon that is 6 out of 10 difficulty and to go deeper into the dungeon and then see mobs that are 4 out of 10 difficulty. Maybe this was set by spreadsheet or some other method, but this level should probably increase in difficulty from the lockpick level. It definitely shouldn’t revert to weaker mobs for no reason. [Suggested by Smitty]

**Comment by TimPickup** [comment]
I'm trying to address this here: #1513

**Comment by Chilly021** [comment]
Resolved.
