### ISSUE TITLE
Martial Artist Sound effect issue in Axe

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1439]
in chaos town the martial artist jumpkick in but then start swinging as if they have a sword but when they connect it says you've been punched [Reported by Jeimuzu Suren]

**Comment by sproatba** [comment]
I don't see anything particularly wrong with the ma here.  I'm guessing this happens with all mas, and is an issue with the sound selection for basic attack maybe?

**Comment by Chilly021** [comment]
We tested this and do not see the same issue. We can re-report it to bring it back up for priority if we see other inconsistencies here.
