### ISSUE TITLE
firestorm targeting

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1440]
there is an issue with firestorm targeting where sometimes certain hexes are completely missed in the firestorm radius. Other times there are hexes that are targeted the first round, then never again for the duration of the firestorm, making it easy for mobs to sit on those hexes in safety. Firestorm should more consistently target the radius area, there should never be a time when a hex in the radius doesn’t get hit by fire for a considerable period of time [Reported by Smitty]

**Comment by Chilly021** [comment]
This is due to the roll of the dice. Similar to any DND, FS can only hit hex that it is successful on for each round. Sometimes you will see it take 3-4-5 rounds for it to apply. Sometimes never at all with extremely unlucky circumstances.
