### ISSUE TITLE
gold-weight-reduction

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1463]
I'd like to see the weight of gold cut in half to minimize the extreme splitting needs, but still make gold weight an important part of the game and a nerf to hand skill.  But, probably 95% of gem sacks end up being sold for 100-200k, which means they require 2 trips back and forth from the seller or the push command.  Alternatiive idea - make gold weigh nothing in town. [Suggested by Algon]

**Comment by jkachhad** [comment]
New rings added to add some meta to hunting and gold carrying.
