### ISSUE TITLE
rebalance oak/leng surface and oak -1 exp/difficulty

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1472]
all portals leading out of kesmai begin in -3 kesmai. There should not be any zones in oakvael that are not a progression in difficulty from -3 kesmai. Oak -1 is a huge waste of time and space… no one who can get to the portals in kes -3 would ever waste their time hunting there. Leng surface may be a bit too difficult for a -3 kesmai portal drop off… an unsuspecting player could die there. I would suggest slightly dropping the Leng surface difficulty (maybe a level or two), and adding current Leng surface difficulty mobs to the power troll zone. [Reported by Smitty]

**Comment by Chilly021** [comment]
This is done
