### ISSUE TITLE
undead axe has too much gold available

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1485]
with a full sack of gems you can bring home 900k in one haul. It was not uncommon for me to make 200k-300k with just an MRP and casting firestorms. Darkice was mad when I suggested it be changed and he’s been hunting there as much as anyone, so that makes me think it’s really really good if he hasn’t already reported it. [Reported by Smitty]

**Comment by TimPickup** [comment]
This should be addressed somewhat by my pull request #1507 

It was using gemsPriceMutatorAboveAverage for some spawns which was making gems up to double their base value by mistake. It should reduce them down a fair bit. Could be re-looked at after
