### ISSUE TITLE
Have 2 second rounds the new standard

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#149]
[Suggested by Slyster]

**Comment by SlysterLOK** [comment]
3 Seconds isnt a long time but it feels like it. After playing with 2 seconds for awhile it feels right. There is enough time to fizzle casters , balm , get runners , move away while hidden , run yourself etc.

Love 1 second rounds but you have no time for all the above. Will be great to use to exp areas you can already easily hunt though.
