### ISSUE TITLE
axe weapon trainer too low level

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1494]
One of the most desirable low level areas in the game are the axe caves across from axe town.  There are numerous weapons in axe people will get and begin using for the first time (SGA, Raxe), and may use those caves for skill.  The axe weapon trainer cannot train you until you're Competent.  Over the course of leveling up mace skill, I went to kesmai 3 times to train over the course of 30 minutes.  This should've been something I can do in axe, due to the level of the zones near axe town. [Reported by Smitty]

**Comment by Chilly021** [comment]
It takes 25 minutes or less to get to competent without training. I am closing this.
