### ISSUE TITLE
Packet Loss

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1514]
Seems there have been multiple reports of repeated packet loss throughout the day. It has beginning to ramp up in volume and being more persistent than intermittent daily. Could be a ddos or could just be a router has been down a long amount of time  [Reported by Chillz]

**Comment by Chilly021** [comment]
Chilly/Twisty/Star/Amanita/Indi have all reported the packet loss.

**Comment by TimPickup** [comment]
maybe a good idea to log ping speed in the save files?

**Comment by Chilly021** [comment]
Seems resolved.
