### ISSUE TITLE
late-game-head-itemization-needs-work

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1542]
you're able to get the games best item for head slot in a few hours of playing.  there should be much better head pieces than griffin skull - and luckily, head is worn by all classes so much less of a balance issue [Suggested by Algon]

**Comment by Chilly021** [comment]
Are we talking about BG? or are we talking about after OL and so on? (Bloodlands, Black 
burrow, and Peaks?)

**Comment by Chilly021** [comment]
I think this was fixed by reversing the attributes. We can always open this back up.
