### ISSUE TITLE
make the rings into a quest

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1573]
been bandied about in chat that since they are so powerful, we could put them into a quest to bridge some gaps and plug some holes. [Suggested by Tenser]

**Comment by Tenscore** [comment]
Basic Premise:

Kesmai's (The Central Bank of Kesmai) bank has missing money.
They're quite positive it has something to do with the Autocrat, who seems to subvert the system a lot.

"Adventurers, The Bank of Kesmai needs your experience in solving a crime.  Somehow, without carts and labor, someone has been stealing from the vault.  It's the people's money!   This is an important matter and requires the utmost discretion.  The culprit has made off with gems and gold totaling 4billion coins!   If we don't get the people's money back, and if the security and trust of the bank is in question...it could destroy the whole economy...  We believe the culprit has something to do with Leng's Autocrat, who's been suspected of underhanded dealings to sew chaos.  The state of politic as it is, we need a small group to secure the banks...er people's money to prevent collapse.  Anything else you find along the way is yours."

--most assume the Autocrat = Vlad, but he's just a stooge for something bigger and more sinister.
Adventurers are tasked with learning who, how, and reporting back to Kesmai.

**Maybe Kesmai is considering 'paper money' to hide the fact that they have no coin as a temporary solution.

And so our intrepid adventurers go to the tower in Leng, defeat Vlad, finding one of the rings and a map that leads to some secret area in Leng' dungeon or UD where a thief has made a hideout.   A Thief that has been now bitten by the vampire. (as-if Vlad had found him and sought to have a word...)

So a minor vampire thats also a thief with tricks.   maybe a nasty backstab.   maybe speed and stalker,
Defeat him for the other ring, and the 4bill that belongs to the bank of kesmai.
(If adventurers keep it, there should be consequences.  Delivery should result in a significant XP reward, and the Kesmai quest giver eating his words on the "Anything you find along the way is yours" comment.)

**and maybe, the thief now knowing he's a vampire, thought he could mingle with the liches in Oak's UD - leaving only a clue to his whereabouts in his Leng hideout.

Simple heist - smash and grab.   and smash and grab again.
as a basic idea...

**Comment by Chilly021** [comment]
I think we decided on this after this. Gem ring is now on Vlad and bank ring is on vendor in UK for 1 mil.
