### ISSUE TITLE
Drinking a DP removes 1st knights quest

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1575]
Drinking a DP removes 1st knights quest HP. Tested by 4 people now. Redoing the quest apparently jumped someones health up to Max when they were not max before, maybe adding on from where they were before drinking the DP [Reported by Draknith]

**Comment by TimPickup** [comment]
Update: someone said it also happened to them when levelling up. So this is more likely not directly related to DPs but likely something like all 1st quest have been reset. When Max HP is next updated via DP or Level, your HP goes down to be capped by Max without 1st quest

**Comment by jkachhad** [comment]
Are players not able to simply re-do the quest?  The reset could be very likely. Quest data is stored independent of the player.  If we had some kind of corruption on the quest database, that could result in max health recalculation.

**Comment by Chilly021** [comment]
I believe this was fixed. Please reopen if otherwise.
