### ISSUE TITLE
exiting at thaum trainers

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1578]
trainers have some sort of logic to prevent exiting on their hex.  Thief trainers have counters which cover this.  Thaums have altars which don't seem to have this built in so you can exit at the thaum training hex. [Reported by Angry]

**Comment by sproatba** [comment]
Yeah, i'm guessing whatever logic is there for the thief trainer is missing something to handle altars on the thaum trainer.

**Comment by jkachhad** [comment]
May need to go through and change all "Altars" to Counters when related to a vendor.  I could add "Altars" to the server-side, but then all Altars (like in Kes lockers) will prevent log-off.  Preventing log off should only work for counters?

**Comment by jkachhad** [comment]
Inspector: Altar found in Kesmai near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		
Inspector: Altar found in Leng near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		(4, 4, [254])
		(20, 17, [1])
		
Inspector: Altar found in Axe Glacier near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		(4, 4, [254])
		(20, 17, [1])
		(27, 15, [1])
		(32, 11, [1])
		(4, 2, [15])
		(7, 3, [15])
		
Inspector: Altar found in Oakvael near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		(4, 4, [254])
		(20, 17, [1])
		(27, 15, [1])
		(32, 11, [1])
		(4, 2, [15])
		(7, 3, [15])
		(26, 6, [10])
		(4, 12, [14])
		
Inspector: Altar found in Underkingdom near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		(4, 4, [254])
		(20, 17, [1])
		(27, 15, [1])
		(32, 11, [1])
		(4, 2, [15])
		(7, 3, [15])
		(26, 6, [10])
		(4, 12, [14])
		(27, 4, [2])
		(13, 5, [1])
		(13, 3, [1])
		
Inspector: Altar found in Bloodlands near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		(4, 4, [254])
		(20, 17, [1])
		(27, 15, [1])
		(32, 11, [1])
		(4, 2, [15])
		(7, 3, [15])
		(26, 6, [10])
		(4, 12, [14])
		(27, 4, [2])
		(13, 5, [1])
		(13, 3, [1])
		(24, 0, [1])
		(24, 4, [1])
		(47, 55, [17])
		(46, 47, [17])
		
Inspector: Altar found in Blackburrow near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		(4, 4, [254])
		(20, 17, [1])
		(27, 15, [1])
		(32, 11, [1])
		(4, 2, [15])
		(7, 3, [15])
		(26, 6, [10])
		(4, 12, [14])
		(27, 4, [2])
		(13, 5, [1])
		(13, 3, [1])
		(24, 0, [1])
		(24, 4, [1])
		(47, 55, [17])
		(46, 47, [17])
		(7, -38, [1])
		(35, 8, [7])
		
Inspector: Altar found in Razalas Peak near `VendorEntity`.
	Solution: Convert to counter.
		(29, 8, [1])
		(30, 6, [1])
		(40, 23, [1])
		(7, 2, [9])
		(3, 2, [2])
		(4, 4, [254])
		(20, 17, [1])
		(27, 15, [1])
		(32, 11, [1])
		(4, 2, [15])
		(7, 3, [15])
		(26, 6, [10])
		(4, 12, [14])
		(27, 4, [2])
		(13, 5, [1])
		(13, 3, [1])
		(24, 0, [1])
		(24, 4, [1])
		(47, 55, [17])
		(46, 47, [17])
		(7, -38, [1])
		(35, 8, [7])
		(13, 27, [1])
		(10, 27, [1])
		(13, 18, [6])
		(13, 17, [6])
		(13, 16, [6])
		(13, 14, [6])
		(13, 15, [6])
		(19, 32, [1])
		(32, 39, [16])
