### ISSUE TITLE
Salamanders make no sound

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#158]
Attack / See sound , Ambient Hiss Sound , Death Sound arent there. [Reported by Slyster]

**Comment by jkachhad** [comment]
I don't seem to see any attack or near by sound. I only was able to find a death sound.  Do you have any replays from Lands of Kes where they hiss when attacking or are near by?

**Comment by SlysterLOK** [comment]
They sounded like a snake / serpent. So whatever they sound like it is what it is.
