### ISSUE TITLE
Wizard NPC will always fumble

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#160]
-4 Wizards ( Male at least ) will always fumble their staff when they attack with melee. [Reported by Slyster]

**Comment by SlysterLOK** [comment]
Update : This is caused by the NPC Wizards using a Shield and Staff.

**Comment by jkachhad** [comment]
I think it's similarly related to BBS allowing swings despite being 2-handed.

**Comment by SlysterLOK** [comment]
Yep it is. Just remove their shield and it is good to go.
