### ISSUE TITLE
No -4 Caster uses Stun

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#161]
I cannot remember which but 1 or 2 casters should use Stun instead of blind in -4. I cannot remember if it were Spectres and Thaums or Specs and Female Thaums. Right now everything blinds it seems. Unless I am just resisting the Stun spells all the time. [Reported by Slyster]

**Comment by Tawnos-LOK** [comment]
This has been adjusted since 2019, looking at the caster AI down in -4 and similar areas.
