### ISSUE TITLE
MainGauche not beltable

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1612]
After the art change and compile I can no longer belt or place my Main Gauche dagger in the sack. I made no changes to the source files other than tweaking the art file it indexes to, so i'm not sure what's going on. I checked the base classes it inherits and nothing changed there either. The original MainGauche is still beltable. [Reported by Wirednuke]

**Comment by Chilly021** [comment]
Should be fixed. @Wirednuke

**Comment by Chilly021** [comment]
Confirmed. https://discord.com/channels/577503035526348810/577503035526348812/969206586125987900
