### ISSUE TITLE
Minos should charge

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#162]
I think the ones in -4 charged in the OG. They also ran but Minos shouldnt imo. [Reported by Slyster]

**Comment by jkachhad** [comment]
They should be charging from a 1 hex away, was there ever a message that they had attacked with a charge? Right now it will just display their normal message.

**Comment by SlysterLOK** [comment]
I am pretty sure their charge was 3 hexes away and it was a gore by horn message if I remember.

**Comment by Tawnos-LOK** [comment]
Checked the Segment files - all of this has been sorted out and implemented.  The Mino's can charge and have weighted attack %'s
