### ISSUE TITLE
Client Crash - Ram Skull Staff

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1627]
Dragging an item over the staff when it is in your locker causes the client to crash to desktop. [Reported by Victor]

**Comment by sproatba** [comment]
This is being cause by the art items not having a category set.  This will be fixed in the next client/server recompile.

**Comment by Chilly021** [comment]
Resolved.

**Comment by Chilly021** [comment]
https://github.com/jkachhad/Stormhalter/pull/1631

**Comment by Chilly021** [comment]
https://github.com/jkachhad/Stormhalter/pull/1617

**Comment by Chilly021** [comment]
https://github.com/jkachhad/Stormhalter/pull/1614
