### ISSUE TITLE
Charge for Twohanded weapons

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#164]
Works ONLY with strict 2 Hand Weapons. Same as jumpkick and works the same just hit with weapon instead of foot. [Suggested by Slyster]

**Comment by dedmist** [comment]
What's the tradeoff for 2H?  It hits hard and blocks better than an RWeap.  It can hit ice dragon and is the skill for the hardest hitting weapon in the game.  Would this change make RWeapons mostly obsolete?  Would the playstyle of a knight differ from that of a MA?

The tradeoff with polekick is that it used MA skill and not on a weapon class that hits all lairs.

**Comment by zrikzlok** [comment]
I think charge for 2h could be viable, but make it take 2 rounds perhaps ? definitely make RWeapons be very usable
