### ISSUE TITLE
Poison stacking

### ISSUE THREAD

**Issue by sproatba** [jkachhad/Stormhalter#1650]
![image](https://user-images.githubusercontent.com/24525708/167050887-9e2fd62f-4a00-497f-996d-573b439a1a66.png)

There seems to be an issue with stacked poison, where the first poison doesn't wear off, but instead starts adding negative damage.    This is causing poison to wear off faster than it should and do less damage overall

**Comment by jkachhad** [comment]
Resolved with the next update. Thanks
