### ISSUE TITLE
NPC stun spell doesn't work

### ISSUE THREAD

**Issue by sproatba** [jkachhad/Stormhalter#1662]
Adding this so it has some visibility, currently NPC stun spell never stuns a player

**Comment by Tenscore** [comment]
our stuns barely effects mobs, too.
same with lightning, and concussion stun-effects.

in fact, many effects don't seem to be included in our spells.  "confused by fire", "slipped on the ice", "caught in the WW"- so they expeditiously jump out of our AOE's. -- This is Wizzy life in SH, atm.

It's sad.

**Comment by Chilly021** [comment]
Retested Stun spell. Looks good.
