### ISSUE TITLE
How do we clean up items created in segment code

### ISSUE THREAD

**Issue by sproatba** [jkachhad/Stormhalter#1667]
#1656 The princess quest is getting cleaned up a bit, but we have a princes scroll defined in segment code now that needs deleted?  I guess it can be left behind safely as it has no real purpose and doesn't affect anything.  Either way would be nice to get it out of segment code.  Need some guidance on how we can clean it up or if we can clean it up.

**Comment by jkachhad** [comment]
The server will prompt me if I want to delete all instances of that type class.  You can remove it safely from the code without issue.
