### ISSUE TITLE
Non NV Seeing through natural darkness

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1752]
I was in Axe Surface Dungeon, taking care of a few mobs, two of which were archers at 3 squares away. I threw my hammer at one killing it, then prepped to throw the other, right as I clicked to throw, night fell. The alread dark cave grew darker, but inexplicably the goblin was still visible in the dark hex, however i could not manage to hit him with my throwing hammer. He was still plinking me however.

(Not sure if just the transition to night time caused an engaged mob to stay engaged at that distance, or if it was related to the fact i managed to attack almost *exactly* as night fell, in anycase the mob was visible in the night time dark hex and able to attack me, but unable to be attacked, and i'm 90% sure those don't have NV) [Report by Amedai]

**Comment by jkachhad** [comment]
Should be resolved on the next update.  All visibility will be properly recalculated when light cycle changes occur.
