### ISSUE TITLE
Moving weapon to belt

### ISSUE THREAD

**Issue by BadAmp** [jkachhad/Stormhalter#177]
Should be able to move weapon to the Belt on the belt screen.   Currently have to move weapon to small icon to get it to work.

**Comment by jkachhad** [comment]
It should be possible to drag items into the specific slots. The issue may be dragging to where the slots are not positioned. I'll test it out and make sure you can drop to a generic location and client + server will decide will slot it should fit into.

**Comment by jkachhad** [comment]
Fixed for version 0.21
