### ISSUE TITLE
coins

### ISSUE THREAD

**Issue by BadAmp** [jkachhad/Stormhalter#178]
Coins that are picked up and put into Bag should auto stack with other coins.  I can put a stack of coins in each item spot.

**Comment by jkachhad** [comment]
It's sort of intended if you drop it into a specific slot. I think you drop it over the backpack icon, it will auto stack for you. I'll test and verify

**Comment by jkachhad** [comment]
Items do indeed auto-stack if you drop them over the backpack icon. If you are able to think of a way to auto-stack them when dropping into a specific slot, I can do it. I want to keep the functionality of being able to place different stacks in to different slots.

**Comment by BadAmp** [comment]
I like that idea...now if you could just stack Balms!

**Comment by jkachhad** [comment]
Hehe, tough sell!  The "take {coin | coins | gold}" command will also stack them to the first instance in the pack.
