### ISSUE TITLE
warm Death no longer works after obtaining Death Resistance

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1822]
"warm Death" has been working fine until recently when I obtained the Death Resistance spell.  
Now, when I try to use the warm death command, I get an error that states "You can't seem to decide which spell to warm".  
Warm Death Resistance works fine though.  

Similarly, I cannot use command line to warm Lightning Bolt.  If I try warm Light, I get the same error above. [Report by LordShu...Lords]

**Comment by jkachhad** [comment]
Resolved in the next patch.
