### ISSUE TITLE
Replays stop recording if you click the exit button in an area where exiting is blocked

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1832]
If you click the exit button while you're in a lair or some other area where you're not allowed to actually exit, it still stops recording your replay for that session.   [Report by crigo]

**Comment by jkachhad** [comment]
Could not be verified.  Testing on 02/28/23 seems to be working properly.  The replay only ever stops if the world state is destroyed.
[World 2023-02-28 14-16-31.zip](https://github.com/jkachhad/Stormhalter/files/10855247/World.2023-02-28.14-16-31.zip)
