### ISSUE TITLE
 Identify Ring doesnt ID 

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#188]
I may be missing something but I cannot get the Identify ring to work. [Reported by Slyster]

**Comment by jkachhad** [comment]
https://i.gyazo.com/44f8475ff147967d5f95cb0ed3298c84.mp4

I recalled from OG that it identified the item in your right hand. I never used it on Lands of Kes, not sure what the functionality there was.

**Comment by SlysterLOK** [comment]
I had it in the wrong hand then. I thought I rememberd ring in right ID left. Either way it works.

**Comment by zrikzlok** [comment]
I can't remember OG, but lands of kes replicates ring must be in left hand and it IDs right hand
