### ISSUE TITLE
Kosh Scales

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#196]
When the time comes have Kosh Scales better than Daisy Scales [Suggested by Slyster]

**Comment by zrikzlok** [comment]
![kosh_armor2](https://user-images.githubusercontent.com/51264376/59398222-69eb1600-8d5d-11e9-8a36-9a2050ec8fcb.gif)
![kosh_armor](https://user-images.githubusercontent.com/51264376/59398223-69eb1600-8d5d-11e9-901a-23b4d053e97d.gif)
do either of these seem reasonable?

**Comment by SlysterLOK** [comment]
I was thinking of something a little less everywhere. But of those the second if my preferred.

**Comment by sproatba** [comment]
This has been partially implemented as Item quality, we haven't specifically added it to kosh, but the potential is there to use where needed.  Going to close this one out.
