### ISSUE TITLE
Casted strength buff doesn't increase MaxWeight until you pick up / drop something

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#1962]
When my knight's casted strength buff is not up (I do have one glower equipped, not sure if that matters), props shows my MaxWeight is 96000. So if I try to pick up 100000 coins it doesn't work, as expected

If I then cast strength on myself, MaxWeight stays at 96000. Still can't pick up 100000 coins.

If I then pick up or drop anything (1 coin, a balm, whatever) MaxWeight changes to 120000 and then I can pick the coins up.
 [Report by crigo.hc]

**Comment by jkachhad** [comment]
Should have been resolved with a prior fix.  Closing.
