### ISSUE TITLE
Give Trog more HP

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#197]
At 12/10 I killed him in 4 hits. Also give him more useable loot to help with -3 and -4 like a death res /  blind res ring [Suggested by Slyster]

**Comment by jkachhad** [comment]
I think 12/10 might be a bit strong for him? I think the goal should be level 5/7 balance?
His loot table does have Blind resistance ring.

**Comment by SlysterLOK** [comment]
Yeah he should be around the level 5-7 range for a good challenge. I did not see the ring. Is it not 100% ( which is fine as long as it is there )?

I refought him on a level 6 Thaum and he was much more difficult fizzling me constantly. On a melee crit he is pretty smooth.

**Comment by jkachhad** [comment]
[Fighter-Trog-Replays.zip](https://github.com/jkachhad/Stormhalter/files/3315813/Fighter-Trog-Replays.zip)

Killed him with a Docker Fighter, 4/4 and 5/5 docker. I think 4/5 had some luck involved - almost died to a stun. 5/5 was a breeze.
