### ISSUE TITLE
Venom Spell Targetting

### ISSUE THREAD

**Issue by jkachhad** [jkachhad/Stormhalter#2]
Currently, as an enhancement, I had considered allowing casters to target which weapon they wish to poison. This prevented having to move daggers between their hands and utilizing "cast at left" or "cast at right" (these commands are still available). 

An additional enhancement may be to implement a "cast" command for this spell, which directs it to automatically cast on the right hand. Furthermore, we could implement hotkey parameters for spells. For example, holding shift and casting venom would auto cast on the right, or casting Cure while holding shift would auto cast on yourself.

**Comment by SlysterLOK** [comment]
Ahhh. I see where you were going with this one. I like it especially if a cast command is implemented to auto venom whatever is in your hands.

**Comment by SlysterLOK** [comment]
Targeting works on belted Items. I am not sure anything needs changing besides a hot key like you mentioned.
