### ISSUE TITLE
Daisy fight balancing

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#201]
Daisy should take 8-12 hits depending on the weapon and deal damage in the 40ish range for her bite attack.  Fire shouldn't be more than 50% of her attacks.  The normal cadence for a low level at Daisy is balm/swing/swing for about 20 rounds of fighting.  This was proven doable (with a decent deal of luck) by a dockbaby with an untrained weapon. [Reported by Asheron]

**Comment by dedmist** [comment]
I went back through the forums to get confirmation

> After having wellllll over 50 fights against daisy with noobs, NT, naked, and even geared chars under level 8, that fighting her on land is much better because she cast fire balls. If you're fighting over level 8 and have good HP then its not as big a deal, the object being is to able to run a balm so you can hit during it.
> 
> Jack and I both tried it a lot a level 3, 4 and 5. 3 being impossible no matter what, 4 being very rough and only on a geared char, 5 NT doable but only in the fire. At level 8 its fairly easy if you know the fight with any class and or gear set up (including naked) in the water or land. but land still gave us more kills.
