### ISSUE TITLE
Quirk taking coins

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#2014]
If you take coins with a command and you have none in your hand or in your sack
 they go into your hand
If you have coins in your sack they go into sack.
With coins already in your hand it says you must have a free hand to do that.
With coins already in your hand and coins in your sack you still get the error but
the game puts the coins in your sack. [Report by Fuddy]

**Comment by jkachhad** [comment]
This should be resolved on the next update when `take` and `sack` command have distinct function on moving into hands vs sack. Ultimately, you will want to change your macros to use `sack gold` rather than `take gold`
