### ISSUE TITLE
Some enemies are attacking through a melee Stun

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#205]
So far I have noticed ranged crits not being bothered by a melee stun. Also have noticed crits blocking while being stunned with their weapon [Reported by Slyster]

**Comment by jkachhad** [comment]
I fixed the first issue with melee stun and creatures continuing to attack. It should have been prevented at the AI level, but I added an additional check for when the attacks occur.

On the second report, was this against possibly animal type creatures? Say a bear, wolf, etc..  creatures that don't have normal block sources (paws, hides, beaks, etc.)

**Comment by SlysterLOK** [comment]
Yes it was! One that stands out is being blocked by a claw!
