### ISSUE TITLE
Custom buttons for Thaum

### ISSUE THREAD

**Issue by dedmist** [jkachhad/Stormhalter#212]
I don't mind that a thaum is more difficult to play, it is a part of their charm.  But they can't play very fast.  Custom buttons for certain actions would help quite a bit.

Cycle DJ button: dj (1) -> 2, 2->3, 3->1.  This is just a name shuffle, so there's a primary DJ target.  Takes 0 turn time.  Also consolidates DJs; if you have 2 and 3 changes to 1 and 2.

dj stop button.

next dj attack 1 button, double click for 2 dj attack

all stop button
all follow button

maintain position, djs use same movement commands as their master

DJ button, click it and click a critter for attack critter, or click a tile for movement, click it and click the stop button for stop

DJ queue button, sets up a first or next command, like the DJ button

Allow DJ commands to be done during wait phase.

**Comment by Chilly021** [comment]
Closing this but bubbled it up to https://github.com/jkachhad/Stormhalter/issues/1216
