### ISSUE TITLE
Knight unable to rez

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#2132]
I am having an issue with my knight not being able to resurrect
It started last night, if i die, my character respawns with 0 health and unable to 
move. other people cannot see me, unless i respawn in front of them.  Also if i am not
at full health i lose 11 hit points per tick, until i heal to full which stops it.  It makes my knight unplayable [Report by Ganj.Knt]

**Comment by Chilly021** [comment]
Resolved
