### ISSUE TITLE
kosh and hand skill blocking

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#230]
seems to not be working properly 19 skill hand, getting rocket. [Reported by zrikz]

**Comment by jkachhad** [comment]
At 19 skill,  you should be avoiding an attack 30% of the time (miss or block), 41% chance that it was a miss, and 59% chance you blocked by hand.
At 15 skill, 16.2% of the time, with 45% as a miss, and 55% as a hand block.
At 10 skill, Kosh should hit you 100% of the time.

These are the numbers without considering dexterity bonus towards dodge/miss. The minimum skill you would need to have some potential of blocking Kosh, with hand skill, is level 12. 

Gauntlets can also provide a bonus towards blocking by hand.

Let me know if you think adjustments are still needed to hand blocking.
