### ISSUE TITLE
Need more commands for Summons

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#25]
Examples.

All, Down
All, Up
All, Release ( de summons )
Etc.

Then individual commands by the # on the summons name.

1, attack 2 will cause Phantasm [1] to attack Phantasm [2] for example.

**Comment by jkachhad** [comment]
I tested "all, (command)", worked. I added "#, (command" functionality, and release as another keyword for begone.

**Comment by SlysterLOK** [comment]
All , Fight / Follow etc work. Couldnt get down or up to work? Thanks for the # command. Will help when using a bait summons out in front when conc Djinn hunting.
