### ISSUE TITLE
skill level advancements

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#263]
We want to fix the rate of skilling at the higher level, but the lower level of skilling isn't exactly unbalanced.  Maybe the character's level can determine the skilling modifer, get a 1x increase every 4 levels, being a 5x at lv 20.  This would also allow a very experienced player to take a new skill line up much faster, but the lower level player still has to learn how to deal with the game before they're ready to move onto other levels... and would help to keep skill from overtaking experience levels. [Suggested by Asheron]

**Comment by dedmist** [comment]
Lux mentioned that per crit and realm skilling is already an option, this should be closed.

**Comment by Tawnos-LOK** [comment]
Closing as per the last comment.
