### ISSUE TITLE
crit kiting 3 step

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#284]
moving 3 hexes away from a mob that can only move 2 spaces causes them to move randomly instead of closing ground.  Was running from kes surface mobs [Reported by Angry]

**Comment by jkachhad** [comment]
This is likely related to the creatures having night vision. Only certain animals on the surface have it. I'm not sure at this time if it should be changed. I think it's  fair that if a humanoid (player or creature) can't see in the night, they are unable to walk beyond their vision. Players have the extra freedom to do so against some risk of running into a wall or other dangers.
