### ISSUE TITLE
bows don't un-knock

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#294]
when you kill a mob with a knocked bow, or move/drop/belt a knocked bow, it does not un-knock.  Crossbows should behave this way, but bows shouldn't imo [Reported by Angry]

**Comment by jkachhad** [comment]
> when you kill a mob with a knocked bow ... it does not un-knock

Are you saying that bows should remain nocked even after delivering a fatal blow to a creature?

Just so I understand, it should be implemented such that moving/dropping/belting a crossbow should cause it to un-nock, but not bows.

**Comment by jkachhad** [comment]
I think I understand better now, will implement as follow:
"Longbows and shortbows will unnock when a character moves, but the crossbow can be carried in the nocked state. "
