### ISSUE TITLE
worldforge windows zoom

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#300]
Worldforge selects wrong tile when using windows zooming (in my case 250% on 4k screen); this isn't an issue on the actual game though. [Reported by Asheron]

**Comment by dedmist** [comment]
I turned off the zoom and had the same issue, there's a mapping problem for a cursor, maybe it has to do with the screen size.

**Comment by dedmist** [comment]
![worldforgemouseissue](https://user-images.githubusercontent.com/2700013/60606134-66591680-9d80-11e9-8365-e37587e1d1b4.gif)
Cursor selection screen coordinates are half of actual cursor selection of 4k screen.

**Comment by jkachhad** [comment]
Looks like this is an issue with DPI and scaling on Windows. You can either unscale the DPI to 100%, but that would make your other applications be small. You can alternatively adjust the Compatibility properties of the application to ignore high DPI scaling.

I'll see if at some point I can render everything to a render target at a default resolution, then scale on everyone's screen.
