### ISSUE TITLE
Rolling Corpses / Loot an adjacent hex causes a disconnect and server crash

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#31]
At the moment a player is able to roll corpses and loot an adjacent hex. Doing this will cause a disconnect and server crash / reset.

Could be an interesting intended perk for thieves if it didnt cause server problems.

**Comment by jkachhad** [comment]
It should be possible in the future without the crash :)  The crash appears to be more of an issue with stacking items. After I fixed item stacking crashes, I was able to roll/loot without an issue.
