### ISSUE TITLE
Thaum fighting style and macros

### ISSUE THREAD

**Issue by dedmist** [jkachhad/Stormhalter#312]
[lokmacro.txt](https://github.com/jkachhad/Stormhalter/files/3364300/lokmacro.txt)
[lokmacro2.txt](https://github.com/jkachhad/Stormhalter/files/3364301/lokmacro2.txt)
[MissJess%27s Macros.txt](https://github.com/jkachhad/Stormhalter/files/3364302/MissJess.27s.Macros.txt)

**Comment by dedmist** [comment]
Using lokmacro.txt my typical concussion strategy would be:
xs (1, stop)
n n
xxa t (2, attack troll that's following 1)
af (all, follow) - this stops the attack as well.  I rarely use all stop
xxa o (2, attack furthest orc)
For ice DJ, I send them n 1 then have them attack on hex
can have them attack dj instead of creatures, especially for invis crits.

**Comment by jkachhad** [comment]
https://dotnetfiddle.net/45t61C

**Comment by dedmist** [comment]
https://dotnetfiddle.net/kVz7lj
