### ISSUE TITLE
 Fire to Air Hex to Fire 

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#326]
This morning I was checking some things. Going from Fire - Jumping Air Hex - To Fire - The Fire I landed on did not do damage until I moved to a normal hex and back on to fire... ? [Reported by Slyster]

**Comment by jkachhad** [comment]
I could not replicate this. I tested by casting Bonfire at Kesmai Locker rope. Was taking ~2hp/tick of damage. Climbed up, casted Bonfire in locker, again was taking damage.  I jumped off to the fire below, continued to take damage.

**Comment by SlysterLOK** [comment]
Dropping from Broodmother down to Nightmare level.
