### ISSUE TITLE
Enter key OK

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#330]
Enter key should activate OK [Suggested by Palad]

**Comment by jkachhad** [comment]
The dialog are prepared by the server and displayed on the client, so adding in custom behavior is difficult. I could move the locate window to the client and add additional packets to handle locate requests.

For now, I've made the following modification:
1. Pressing tab will cycle focus between textboxes and buttons available on the window.
2. Pressing escape will close the window (if it can be closed)

To handle the locate window without any mouse input, the textbox will be auto-focused. After typing your input, you can press tab, then enter.
