### ISSUE TITLE
hoodwink change

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#337]
Moving coins into my hand to cast the spell costs 5 rounds (belt, coins - which is several clicks, warm, cast, unbelt)  Can this be a check - coins at feet, coins in hand, coins in sack?  Maybe set a level for how many gems, a slider that goes from 1-10, each being 30 gems; or the maximum you can afford under that. [Suggested by Asheron]

**Comment by dedmist** [comment]
Also would be nice to target a location, instead of having to pick up and throw each one.

**Comment by SlysterLOK** [comment]
Maybe just have the spell check for coins in backpack then a pop up ( like you are splitting gold stacks ) shows asking " How Much? " Then just say whatever amount you need.

A target hex would be pretty neat. Right now I think you can create bulk and they drop at your feet.
