### ISSUE TITLE
Can't drag items

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#360]
Somehow managed to bug the game to where I can't drag items.  They just reset to their location after a fraction of a second [Reported by PostumusAgrippa]

**Comment by dbretwolfe** [comment]
I'm pretty sure this occured after I was stunned while dragging a balm

**Comment by DevJonTaylor** [comment]
+1 
Entered Kesmai -2  able to drag items as I came into a zoo and needed a balm.
used the balm then I was hit with a curse from wrath.  Went to use balm again and was unable to drag the items.  Went upstairs finished battle and still unable to drag.  Left dungeon still unable to drag balm.  Exit to character select and went back in and then able to move items again.

Re-entered -2 and finished zoo without any wraths to note.  

Found a wrath and cursed.  Issue is replicated.

Attached are the pictures of my character.  I attempted the same thing right as I was about to hit Comment button and I was unable to replicate.  So perhaps something to do with the time of day?

<img width="293" alt="Screen Shot 2019-08-16 at 3 53 28 PM" src="https://user-images.githubusercontent.com/31380713/63198028-176cf500-c03f-11e9-87ac-04900056c167.png">
<img width="297" alt="Screen Shot 2019-08-16 at 3 53 23 PM" src="https://user-images.githubusercontent.com/31380713/63198029-176cf500-c03f-11e9-91e1-5c9c35461ae7.png">
<img width="311" alt="Screen Shot 2019-08-16 at 3 53 16 PM" src="https://user-images.githubusercontent.com/31380713/63198030-176cf500-c03f-11e9-93ea-350394c4a250.png">
<img width="466" alt="Screen Shot 2019-08-16 at 3 59 39 PM" src="https://user-images.githubusercontent.com/31380713/63198031-18058b80-c03f-11e9-9fdb-e3d71359531d.png">
<img width="472" alt="Screen Shot 2019-08-16 at 3 53 44 PM" src="https://user-images.githubusercontent.com/31380713/63198032-18058b80-c03f-11e9-96b3-15403d3eff69.png">
<img width="297" alt="Screen Shot 2019-08-16 at 3 53 37 PM" src="https://user-images.githubusercontent.com/31380713/63198033-18058b80-c03f-11e9-82c5-d82e30c3795c.png">

**Comment by jkachhad** [comment]
Thanks! I was able to watch your replay and looks like this occurs when you are targeting on the client-side, and then get fizzled by an offensive spell. It's likely not clearing the target properly.
