### ISSUE TITLE
Spell Caster

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#375]
While on the water I had an orc spell caster try to cast his web on me. It hit him instead since you can't cast that onto water. Orc spell caster should move straight to MM. [Reported by Marcoux]

**Comment by jkachhad** [comment]
Looks like this is a bug related to using the same algorithm for movement and spell path. I'll have to refactor it a bit to separate the logic. Since the Orcs have an aversion to moving into water because they can't swim, their spell path also fails.
