### ISSUE TITLE
Spell Caster - 2

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#376]
It seems like the spell casters on water are broken also. The ones in Oakvale will cast several times, and then run away. Wizards don't seem to cast MM. Not sure what they're casting but they chant three times and run away if they are on water. Thaums also don't cast stun first and go straight for death - might be working as intended. [Reported by Marcoux]

**Comment by jkachhad** [comment]
- Entities mobility can be assigned with CanWalk, CanSwim, and CanFly. These caster are marked with CanSwim, so they can go on water. 
- The ability to breathe water is independent of their mobility. It's likely the caster are able to swim, but can not breathe water. They eventually drown.
- Fixes may be to mark these casters with the ability to breathe water (they may do so on the NG), or modify the AI to [cast once, move, cast again] restart the drowning timer.
