### ISSUE TITLE
Venom spell

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#383]
When cast, the venom spell should automatically apply to whatever appropriate weapon rests in the right hand.  If no appropriate weapon exists, the spell should fizzle. [Suggested by RaloMyth]

**Comment by jkachhad** [comment]
The alt key can now be held to auto-cast when on a priority selection (right hand, left hand, belted daggers, then belted weapons). Using the 'cast' command performs a similar function. Anything else will provide a target to manually select a weapon.

Thank you for the suggestion!
