### ISSUE TITLE
Visibility through Darkness or Secret Doors is not working as expected

### ISSUE THREAD

**Issue by yarrim** [jkachhad/Stormhalter#388]
Two issues that I think are related. I suspect visibility is not being checked after a crit has acquired a target entity. SecretDoor-LOS replay shows an example where a secret door closes, which should prevent a crit from attacking through that space, yet doesn't. Darkness-LOS replay shows an example where crits continue to attack after darkness is cast on the tile, yet lose tracking once I move.
In both cases, I would expect crits to lose the ability to see me. 
Additionally, in the case of the Secret Door, once I move to adjacent the door, I regain visibility of the crit on the other side and can cast through the closed door. After killing the crit with a spell, the sprite remains visible on the client and can be 'look'ed at, but not fought or targeted with a spell.

**Comment by yarrim** [comment]
[Replays.zip](https://github.com/jkachhad/Stormhalter/files/4435512/Replays.zip)

**Comment by jkachhad** [comment]
Thank you for the detailed report and replays. I was able to reproduce the issue very quickly and should be resolved in the next update.
