### ISSUE TITLE
Poison Cloud randomly moves / bounces and does not poison.. Just blinds enemies

### ISSUE THREAD

**Issue by jkachhad** [jkachhad/Stormhalter#4]
I was able to reproduce the random movement. I prevented both Poison Cloud and Whirlwind from moving through closed doors and observed the intended movement. Please retest when able.

I will keep this issue open for implementing poison.

**Comment by SlysterLOK** [comment]
The targeting issue I mentioned before also seems to be fixed. I can now cast N N E for example and it go East. Before N N E would cause the WW / PC to travel North.

**Comment by jkachhad** [comment]
Fixed for version 0.7.0 - It will blind and poison.
