### ISSUE TITLE
Webs casted by mobs, Conc Wizzes in Ud

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#409]
-OaK-  I let an orc cast 2 webs on ground, and ran back and forth on the two 25 times, only getting stuck once, as well with spiders that sit in webs, multiple attempts to get stuck, the probability is very, very low. Also, I have yet to be stunned by a conc wiz in UD. Or when i drop a fire bottle and it explodes.(this chance seemed to decrease in OG the bigger you got, however at current lvl am just starting to be able hunt here, 17, 7th dan) [Reported by Taishu]

**Comment by jkachhad** [comment]
- I checked the web casts - It seems to interrupt movement as expected. May have to consider adding a scalar based on magic skill?
- Chance to be caught is based on Level and Willpower rolled against d20. Maybe potentially consider 5% minimum chance.

- Fixed concussing not stunning properly.

- I don't recall Naptha ever causing a stun when you dropped it?
