### ISSUE TITLE
salamanders

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#410]
Salamander mobs are scared of own fire, if they cast fire on your hex, when they are not your hex, they run away from it, if they cast it sitting on your hex, they will sit and fight. Also mobs caught in the fire, do not try and run, they will sit until they all die, even if i leave the hex. [Reported by Taishu]

**Comment by jkachhad** [comment]
Tested this out for a bit with salamanders. They didn't seem to have an issue casting on my hex then coming onto it.
