### ISSUE TITLE
minor again

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#420]
no text saying you were hit by concussion and you cant throw concussion into the wall it fizzles or just doesnt work [Reported by Ezeek]

**Comment by jkachhad** [comment]
I don't think you could ever cast concussion into a wall, I may be mistaken. I fixed the issue with the text.

**Comment by jkachhad** [comment]
In the OG version it was possible to target walls, in Atilla's version is not possible. I'll leave it the latter way.
