### ISSUE TITLE
Ruins Art: [104] Portal Pillar

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#464]
[Suggested by Lux]

**Comment by jkachhad** [comment]
Create something like this:
![00156](https://user-images.githubusercontent.com/1934897/130501763-43d41f49-3f28-405c-8205-c88c23f124e9.png)
for this:
![00104](https://user-images.githubusercontent.com/1934897/130501844-0f21caf8-68c2-475d-a96f-b5c43d8baca4.png)
