### ISSUE TITLE
Ruins Art: [371] Stalagmite

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#465]
[Suggested by Lux]

**Comment by jkachhad** [comment]
Create this:
![00156](https://user-images.githubusercontent.com/1934897/130501443-a49ecc17-8885-487c-860b-3b3098f48d89.png)

For this:
![00371](https://user-images.githubusercontent.com/1934897/130501384-82fed592-fc4d-413e-a66c-f1c218914c5c.png)
