### ISSUE TITLE
Disconnect when leaving lockers through window

### ISSUE THREAD

**Issue by surfotato** [jkachhad/Stormhalter#473]
![image](https://user-images.githubusercontent.com/85204505/120408460-f05ee080-c303-11eb-9cb6-ce7e3b74ba31.png)

**Comment by jkachhad** [comment]
Fixed. Another bug revealed by fixing #382.  Visibility updates triggered twice, once when teleported by the sky hex, and another when moving.   Only a single update is now sent, even if two or more visibility changes occur.
