### ISSUE TITLE
Moving into grate at kesmai -4 by stairs causes disconnect

### ISSUE THREAD

**Issue by surfotato** [jkachhad/Stormhalter#475]
![image](https://user-images.githubusercontent.com/85204505/120429244-e8199c00-c329-11eb-860d-4d04d75e6a9d.png)

**Comment by surfotato** [comment]
Maybe related. Running into walls in town also causes this. 
![image](https://user-images.githubusercontent.com/85204505/120431413-4eec8480-c32d-11eb-86bb-70e9ebf2802e.png)

**Comment by jkachhad** [comment]
Should be resolved v0.64.1.  Looks like the bug fix for #382 exposed some other issues related to visibility calculations. The VisibilityDelta can now return null, when no change has occurred.  Thanks!
