### ISSUE TITLE
Avoid pathing through air tiles

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#476]
[Suggested by surf]

**Comment by surfotato** [comment]
![image](https://user-images.githubusercontent.com/85204505/120558524-75a1ce00-c3b4-11eb-81f2-2a414aa0b119.png)

**Comment by jkachhad** [comment]
The client is currently not told the difference between ground and sky terrain. It is told the when a particular terrain is impassible. Should we make it easy to path around sky hexes, or should movement have to be done with care when playing near them?

**Comment by jkachhad** [comment]
This should be resolved in the next path. Sky terrain cost changed to 6 from 3.
