### ISSUE TITLE
Can't dispel illusions as wiz

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#478]
[Reported by surf]

**Comment by surfotato** [comment]
![image](https://user-images.githubusercontent.com/85204505/120593733-c2a59480-c3f4-11eb-94a6-ad35595bfff0.png)

**Comment by surfotato** [comment]
The bottom is 3 illusions over an air tile.

**Comment by jkachhad** [comment]
Fixed, will deploy later as a hot-fix.
