### ISSUE TITLE
"take gold from counter" doesnt work for Sven

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#480]
Multiple counter issue? [Reported by surf]

**Comment by jkachhad** [comment]
There's a differentiation between an altar and a counter. I'm not sure if that should matter much in the context of this command. 
Counters can only be accessed from one direction, but an altar can be accessed from any direction. 

I can make the command ignore this if you still consider this a bug or feature.

If you do "take gold from altar" -- It will work.
