### ISSUE TITLE
"take [item] from sack" doesn't work

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#483]
Can't move things from sack to hand, and maybe vice versa. [Reported by surf]

**Comment by jkachhad** [comment]
I'm not sure we if we can implement this as "take <item> from <location>" conflicts with the command. I could check if Location specifies a container type (ring, belt, etc.). I'm not sure if anyone even uses this as a command frequently? I'll have to make it low priority for now and as a suggestion.
