### ISSUE TITLE
Recall ring to the same spot in Oakvael disconnects

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#484]
Tested at a few spots including recall ring seller: Pearl Oakvael 7, 18, [10]. [Reported by surf]

**Comment by jkachhad** [comment]
Likely similar to the other visibility changes crashes that are occurring when your location doesn't actually change. It may have been fixed in the last patch, but I'll test.

**Comment by jkachhad** [comment]
Fixed on next update. Thanks!
