### ISSUE TITLE
Keep help spell when changing hotbars

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#486]
When dragging a spell off a hotbar, flip to another hotbar while holding the spell. The spell changes to the spell in the same same slot in the new hotbar. This is unlike holding an item between rings and sack. [Reported by surf]

**Comment by surfotato** [comment]
Title should be "Keep **held** spell".

**Comment by surfotato** [comment]
This can crash:

- Hold spell in hotbar.
- Flit to another hotbar that does not have a spell in that location.
- Spell icon will dissaprear, drop spell.

**Comment by jkachhad** [comment]
Resolved for v0.67
