### ISSUE TITLE
Create documentation for worldforge use

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#487]
[Suggested by surf]

**Comment by surfotato** [comment]
I tried to at least cover the questions you answered so they dont have to be asked again by others. It's rough and I made assumptions, but the UI seemed pretty straightforward (except for treasure hordes) so hoping it's mostly right.

I wanted to put this in the wiki, but I don't have permissions to post images. Should we put it there or somewhere else?

I have this in Google Docs and Slides if it helps too. Attached a sample PDF for now.
[WorldForge Quickstart.pdf](https://github.com/jkachhad/Stormhalter/files/6602020/WorldForge.Quickstart.pdf)

**Comment by jkachhad** [comment]
Looks like a great start. Would you consider working on it via the wiki? http://www.stormhalter.com/wiki/Main_Page
You could likely get others involved, as I know Slyster and Fireal have been checking it out as well.  

If you prefer the PDF, that's fine as well. Once more sufficiently defined, we can port over to the wiki.

**Comment by surfotato** [comment]
I started on the wiki, but adding images was disabled. PDF is just for now to share it, I think it's better if it's somewhere editable.

**Comment by surfotato** [comment]
Moved everything over.
