### ISSUE TITLE
Sometimes script contents does not show in WorldForge's Spawns tab

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#489]
[Reported by surf]

**Comment by surfotato** [comment]
You have to click back and forth from the On events tabs to make it show up. Easy to reproduce by clicking through spawns, not sure exact steps.

![image](https://user-images.githubusercontent.com/85204505/120879448-463bbe80-c578-11eb-8b8c-567864d242bf.png)

**Comment by jkachhad** [comment]
Resolved on next update.
