### ISSUE TITLE
Cant pick up items after "sack gold" while dragging item

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#491]
[Reported by surf]

**Comment by surfotato** [comment]
(Was in Kesmai -3)

1. Have gold and sackable item on the ground.
2. Click on portrait window. I think you cant be viewing the sack.
3. Drag item over sack icon but don't let go.
4. Use "sack gold" command.

Dragged item will disappear from cursor but item on the ground will stay transparent. Move to an empty hex and item will be visible on that ground but unusable. Items on original hex will be locked until the unusable ground item is viewed.

Broken transparent gem.
![image](https://user-images.githubusercontent.com/85204505/120966999-d403df00-c71b-11eb-88fc-62be5f52f8f7.png)

Unusable gem on adjacent hex.
![image](https://user-images.githubusercontent.com/85204505/120967028-de25dd80-c71b-11eb-8e96-48930f444e0b.png)

**Comment by jkachhad** [comment]
Resolved
