### ISSUE TITLE
Add gold value as a property of ItemEntity

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#494]
[Suggested by surf]

**Comment by surfotato** [comment]
Towards making this shorter:
![image](https://user-images.githubusercontent.com/85204505/121767704-d0eb6300-cb0e-11eb-8c26-47dd2e6dbf28.png)

Name too? More?

**Comment by jkachhad** [comment]
ItemEntity has three properties related to it's value:

- `Price`: Gets the variable price for this instance (+ or - from base price).
- `BasePrice`:  Gets the base price for this instance. Typically this property is overridden by a class, for example a `SteelDagger` may be defined as such:

`
public class SteelDagger: ItemEntity
{
      public override uint BasePrice => 10;
}
`

- `ActualPrice` - Gets the actual price for this instance, the sum of base price and variable price.

A steel dagger by itself is worth 10 gold, but if it drops in a dungeon, it maybe actually have Price = 5, for an ActualPrice of 15 gold.  I did it this way to minimize how often we have to set the price on something, there is always a BasePrice. Gems have a configurable BasePrice that's set in the constructor.  They are randomized around their BasePrice by 20%, check the `gemsPriceMutator` function for (Segment) internal script.


For StockEntry, the price is the `SellPrice`, not so much how much that item is worth.  We want the player to buy at a high value, but can't sell it back for the same.
