### ISSUE TITLE
Items slot name background

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#499]
I think adding a name to the empty inventory slot would be nice to have. When you first start its hard to tell which slot is which.

![itemsbackground](https://user-images.githubusercontent.com/86327873/123005451-254ed800-d384-11eb-842a-eb0ad2fd1a33.JPG)

**Comment by jkachhad** [comment]
![image](https://user-images.githubusercontent.com/1934897/123554833-d499ff00-d736-11eb-87ca-e387f68699d7.png)

Implemented for v0.67. Great suggestion!
