### ISSUE TITLE
Stun duration when running into a wall.

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#500]
If you walk into a wall 1 hex from you, you get stunned for 3 rounds. Normally you would hear a Bong sound but dont get stunned from that distance.

1 hex = no stun but Bong sound. (right now you get stunned 3 rounds)
2 hex = 3 rounds stun ? (right now you get stunned 5 rounds)
3 hex = 3 round run ? (right now you get stunned 9 rounds)

![1hexstundiagonal](https://user-images.githubusercontent.com/86327873/123006137-406e1780-d385-11eb-9f64-20135df0b8ee.JPG)

**Comment by jkachhad** [comment]
Thanks for the clarification. Stuns are now based on a path requested and the distance moved. I think this is a better representation of running into a wall. Requesting 3-hexes is considered a "run" command, which implies faster speed.  If you only moved 1 hex with this command, you may get stunned for 2 rounds (6 ticks). 

```
var pathSpeed = pathing.Length + args.Path.Count; /* Path requested and moved. */
var stunRounds = pathSpeed switch
{
	(> 0)	=> pathSpeed / 2,
	_	=> 0,
};
