### ISSUE TITLE
Wight kesmai -2 not casting

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#501]
In Kesmai -2

Wight should be caster and try to run away if im too close from them until they get low mana from casting curse, they will run into the player.
Right now Wight act just like a normal melee crit, run at me directly trying to melee me only.

![wightmelee](https://user-images.githubusercontent.com/86327873/123007399-22a1b200-d387-11eb-9f5c-2ed3c0470cb6.JPG)

**Comment by jkachhad** [comment]
Resolved with v0.67
