### ISSUE TITLE
harming self triggers self-defense message

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#502]
as a newbie MA, I fumbled a jump kick and 'sprained my ankle.' I also got a message notifying me that I had been attacked by myself. Hitting myself as a mage with an AOE spell does the same. Killing myself with my own spell doesn't seem to give me Karma, though. [Reported by korazail]

**Comment by jkachhad** [comment]
Resolved with v0.67. Thanks!
