### ISSUE TITLE
Hole hex for trog

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#503]
![CANNOTcd](https://user-images.githubusercontent.com/86327873/123559426-f6f94000-d769-11eb-9980-43f759f38ab9.JPG)

When you go hunt the Trog, there is a Hole Hex to go down and you can only use the Down command and lose HP. You should be able to use also Climb Down because there is a ladder down the hole to climb up.

**Comment by jkachhad** [comment]
Fixed for v0.67
