### ISSUE TITLE
Cannot use dot for the character name

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#505]
![dotdotname](https://user-images.githubusercontent.com/86327873/123560696-d7661580-d771-11eb-9813-5dd7e8794b77.JPG)

We should be able to use a dot in the character name to make some kind of space or if we wish to add a guild tag or something or a title
example:  Sensei.Bobby  or Bobby...SF for a guild tag

Currently we cannot seem to be able to use space or dot.

**Comment by jkachhad** [comment]
Guild tags in the future will be automatically appended to your characters name, similar to other MMOs. I'll enable this for now, then leave it optional for players to rename their characters when guilds are implemented.
