### ISSUE TITLE
Yellow footstep click again to remove

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#507]
In the current server where i play, when i select like 3 yellow footstep where i wish to walk to for example, if i click once again on that 3rd hex with the yellow footstep it will remove that 3rd yellow footstep and make it only 2 hex.

samething if i select a 2 hex move with the yellow footstep and click again that 2nd hex it will remove the 2nd hex and make it only 1 hex.

Maybe you guys wanted it that way, maybe its not a big deal also, just a little different and we have to get used to it but i wanted to tell that there was a difference

**Comment by Chilly021** [comment]
I think this is as intended. Can bring it up later if it becomes a pointed issue.
