### ISSUE TITLE
Loot tile command

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#509]
This was not from the OG but it's inspired from a server some of us were playing.
I think using a loot command would be very interesting for Stormhalter and not be forced to carry around fire potion to burn all corpse on a tile like the wizard can do.

The way it was working, if you select to see closer the tile you are standing with the crit you killed. you could type: loot
and this command was searching all the loot at once on all the body from that specific tile. 

Like i said this was not from the original game but it was a very enjoyable QoL change alot of us liked.

**Comment by jkachhad** [comment]
I believe there has to be some separation of classes for value. If all the classes could do the same thing, there would be no point to playing another. The ability to burn large areas, and even remove trash drops is unique to a wizard, no other class can do it. Quality of life change for sure, but I think it will take away from a few mechanics we could implement.

Imagine we implement a boss that requires you to search corpses from a specific item as part of a mechanic/challenge to that boss. Bringing a wizard might be beneficial for that party, the same way you might take a thief to Daisy for a baby knight to charge in and get that final hit. 

I'll leave this as a suggestion for now.

**Comment by Martindag93** [comment]
yeah i get the point, i think having different strength and weakness for each class make stuff interesting. I would understand if you want to keep it like it was.
