### ISSUE TITLE
Adventurer Buff

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#512]
Here another suggestion i did for another server to avoid having a lot of people in every corner of your server sparring their skill while watching some netflix.

The main idea here would be to make hunting like the most efficient way to actually get skill and not sparring in town.

My idea would be some kind of Adventurer buff you would get in your buff bar that would give you a decent amount of skill gain for hunting.
To get this buff you will need to kill 1 crit of a right level range from you ( a lvl 18 that kill a crit lvl 3 wont get that buff for example).
The buff could stay for 2min or something like that and killing more crit of your level would reset that timer everytime.

You could make the skill gain default from the OG for those that want to level it doing towncasting very slowly. Or hunting stuff around the dungeon to get that buff for a decent skill gain bonus.

I think this buff will also discourage a lot of people that wish to script even if its not legal here or try to automate skill etc.

I think also this buff will force some magic class to avoid cleaning a huge area with their AoE spells like Whirlwind or Poison cloud. Yeah they could still do it to get EXP and Money but doing it, will remove all crit around and you wont be able to keep your adventurer buff up to get more skill.

![HuntingBuff](https://user-images.githubusercontent.com/86327873/123564103-11d9ad80-d786-11eb-97b3-5497c1034a0e.JPG)

**Comment by jkachhad** [comment]
I'll close this out as it is already implemented.
