### ISSUE TITLE
Make all weapon skill useful (early, mid and end game)

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#513]
Here another suggestion, i feel maybe we should eventually add some viable weapon for all the weapon skill. Some weapon like the Flail or threestaff are completely useless in the OG, it would be very nice to have a good variety of weapon choice for new player, mid level and end game by adding them in a quest or a boss drop etc

I still think it would be cool also some weapon wouldnt be class specific,

Im thinking about a MA using a katana for example
or a wizard using a halberd
etc
i think this would be pretty interesting have positive to allow player to have many build available to play with

**Comment by Chilly021** [comment]
I think we are slowly scaling these up. Dagger now is faster and has a little bit of a boost. Staves have been upped just a little and certain other weapons have been implemented.
