### ISSUE TITLE
Cannot climb down Leng hole to temple

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#518]
![lenghole](https://user-images.githubusercontent.com/86327873/124200359-23cb9100-daa3-11eb-8435-3cda0da277f2.JPG)

Samething then the Hole for going down to the Trog in Kesmai ( I guess its the hex himslef the problem)

You cannot Climb down that hole, you can only do Down and take fallen damages
(there is a rope once you are down to climb up which is fine.

**Comment by jkachhad** [comment]
Fixed for v0.67
