### ISSUE TITLE
Hand blocking effectiveness curve

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#519]
I went to Axe with a naked MA at 17 hand skills to compare it with a MA s12 hand skills and i could barely survive with a zoo of 10 crit on me.
I see a huge difference of damage and accuracy hand skill 12 VS skill 17 which seem fine
But the blocking of hand skill 12 VS skill 17 feel very similar, a high skilled MA even naked should block so much more.

**Comment by sproatba** [comment]
closing this one out as it's very difficult to do anything with.  Gauntlets, sheilders, dex rings all add significant amounts of blocking.  Currently cgs and 2 dex account for more blocking than 5 levels of skill.  So I would expect you to end up worse off in the given situation.  Especially when it comes to archers.  All these are separate issues being delt with in other discusions
