### ISSUE TITLE
Delay bypass to any facet on double right click

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#523]
I made a macro with my Mouse to double click really fast in loop at 100ms and i was able on any facet to bypass the action delay set (1.5s,  2s,  3s) while walking or fighing a crit, i could do like a triple move without any delay or like a triple swing while holding it.

**Comment by jkachhad** [comment]
Can you record a replay, or tell me a time stamp where this might have been possible. Ideally the server should lock any future actions for the turn time. I'll check on my own to see if I can submit multiple movement packets to the server with even a lower rate.
