### ISSUE TITLE
New facet delay since we added Ruby seem off

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#524]
I timed my average movement for each facet based on a average of 10 movement each.

Agate / Beryl Should be 3sec,   the real movement is 3.5s to 4s
Pearl should be 2sec, the real movement is 2.5 to 2.75s
Opal should be 1sec, the real movement is 1.5s

**Comment by jkachhad** [comment]
This is likely just from lag, the server is under some load with the recent of the two facets.  CPU utilized has jumped from 50% to 88 %. I'll likely measure some metrics on server performance this weekend then implement one method for optimization.
