### ISSUE TITLE
Annoying little delay after any action

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#525]
No matter which action you do ( moving, fighting, looking at a hex, selling) there is always a little lag of 300-400ms behind any of those action compare to the normal server we are used to play.

**Comment by jkachhad** [comment]
I think this is likely due to the addition of the new facets. It’s good we’re able to see that there is impact from additional facets. I do have thoughts on improving the efficiency of some processes.

**Comment by Martindag93** [comment]
After removing the 3 facets, the delay is much much better
