### ISSUE TITLE
Items Amount press Enter for Okay

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#531]
![Enter_OkayAmount](https://user-images.githubusercontent.com/86327873/124370171-4d6eee80-dc42-11eb-987b-aa0fc00812c2.JPG)

It would be great if we could press Enter on the keyboard to do the Okay button on the Items amount windows
and do Escape to Cancel.

**Comment by jkachhad** [comment]
Implemented in next patch.
