### ISSUE TITLE
Take gems from counter with hand full

### ISSUE THREAD

**Issue by Martindag93** [jkachhad/Stormhalter#533]
I have 10 gems on rolf counter and a shield + sword in my hand.

If i do take gems from counter
a text say, you must have a free hand to do that and for some reason i cannot remove the shield or sword from my hand.
i need to move 1 hex from the tile i was to be able to remove it again.
and if i do lets say remove my sword, it disappear completely from the screen and if i move to a hex again it will reappear.

**Comment by Tawnos-LOK** [comment]
Retested a bunch of used cases related to this - no longer causes a conflict with hands full.  Also, 'sack X from counter' is handy as well to move gems or other items into the sack from a counter.
