### ISSUE TITLE
Treasure conjurer is stuck to PC

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#539]
Went by conjurer, somehow stuck now. [Reported by surf]

**Comment by surfotato** [comment]
![image](https://user-images.githubusercontent.com/85204505/124401822-94abbc80-dce0-11eb-836e-eaa673e0b4f7.png)

**Comment by surfotato** [comment]
Re-enter lockers fixes this unless you reproduce.

Reproducible: walk out on this air hex.
![image](https://user-images.githubusercontent.com/85204505/124401901-39c69500-dce1-11eb-8116-83bb1f5ba584.png)

**Comment by jkachhad** [comment]
Fixed
