### ISSUE TITLE
have town npcs prefer to avoid water

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#541]
[Suggested by surf]

**Comment by surfotato** [comment]
![image](https://user-images.githubusercontent.com/85204505/124402214-b2c6ec00-dce3-11eb-84a2-5fe5deaeff15.png)

**Comment by Tawnos-LOK** [comment]
Checked the Segment file - Biscuit is the only non-shark lawful that has CanSwim = True and can take a dip in the water there.  The other town NPCs do avoid the water.
