### ISSUE TITLE
Axe statue, not a statue

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#542]
[Reported by surf]

**Comment by surfotato** [comment]
![image](https://user-images.githubusercontent.com/85204505/124403783-d93d5500-dcec-11eb-9aa4-7d66dbc46da8.png)

**Comment by SewerCzar** [comment]
Comment: Body when tanned drops the "Tanned jacket."

Body type they're set for is "97":

    var peacekeeper = new Peacekeeper()
    {
        Name = "statue",
        Body = 97,
