### ISSUE TITLE
Monsters with no night vision have 2 hex vision at night

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#543]
Monsters such as orcs, etc with no night vision cannot see you from 3 hexes away outside during the night time so they wander off the screen.

Monsters with the "Night vision" flag see you properly from 3 hexes away at night as well as through darkness.

**Comment by Tawnos-LOK** [comment]
Is this considered an issue or working as intended?

**Comment by jkachhad** [comment]
I would think working as intended. If something doesn't have night vision, it shouldn't be able to see past 2 hexes at night.  The second part of the post might be an issue.  I think you could peer into Darkness if you were next to it, but not if you were 1+ hex out?
