### ISSUE TITLE
Set damage values appear to be mitigated by something

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#546]
This might be intended but my MA had a 1400 defense value and was taking less damage from set value monsters than intended - from kwolf I took 7, 11, 14, 12, 13, 12 damage. His damage range is 10-45. Giant also did far less than damage values, and I believe Drake did as well.

My friend with 1100 defense was saying he took more damage than me.

It seems defense variable might be reducing static damage? Not sure if intended.

**Comment by SewerCzar** [comment]
Example - My 1400 defense MA was fighting Giant. He this attack:
new CreatureAttack(12,      60, 85,     "The giant stomps on you.",
                                                        new AttackProneComponent(25), 
                                                        new AttackStunComponent(10)),               40" 

My hit points went from 191 to 175. 16 damage. Value set is 60-85. Is it taking the first two numbers? I dont know maybe my logic is mistaken.

**Comment by jkachhad** [comment]
Resolved. Expect some bigger damage outputs on the next round of play-through.
