### ISSUE TITLE
Fire damage appears to be low

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#547]
Comments from multiple people - wizard fireball damage feels lower than OG, and the orcs in -2 and -3 also deal less. I believe Fire skills are doing less damage than intended with the same skill - scaling seems off. Maybe f/i is too high right now? 

I'll scale up fireball damage for now but let me know if it's found to be low so I can scale it back eventually. Other mobs took barely any damage from "level 4.5 fire ball" cast by a goblin

**Comment by Tawnos-LOK** [comment]
This was adjusted in a patch shortly after I started
