### ISSUE TITLE
Two monster casting issues compared to OG

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#551]
Monsters such as wraiths, thaums, etc will run 2 hexes away to cast their lowest value spell once they've regenerated mana. If they ran away to cast a new death that would be challenging but they go for their lowest spell. If I made death cost less for them that could actually be challenging... You'd have to target casters before they went for a big damage spell again. I kind of like that idea.

Other issue is monsters cast their spells in random order - Wraiths will cast 2 blinds 1 death, etc. Not actually a terrible thing but doesn't match OG mechanics.

**Comment by jkachhad** [comment]
The AI determines a list of spells available to cast based on current mana. It likely only returns the single spell when the mana becomes available. There are a few options to help randomize the encounters.

1) Implement a cooldown on low level spells to prevent them from chain casting.
```
goblin.Spells.Add(new CreatureSpell<FireballSpell>(
    skillLevel: 4, cost: 6, 
    mantra: SpellHelper.GenerateMantra(), instantCast: false),          100,        TimeSpan.FromSeconds(30.0))
```
which is equivalent too
```
{ new CreatureSpell<FireballSpell>(
            skillLevel: 4, cost: 6, 
            mantra: SpellHelper.GenerateMantra(), instantCast: false),     100,     TimeSpan.FromSeconds(30.0) },
```

2) You'll notice above there is now a "100" -- this is the weight of the spell when randomizing which spell to cast. You can have it prioritize certain spells with higher weight. For example, if you want Death to be cast 3 times more than Curse, you could assign weight of 75 and 25.
