### ISSUE TITLE
Darkness Spell from monster spell variable list causes a 1x1 instead of 3x3 spell

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#552]
Need another spell flag that's 3x3 or default to be 3x3 for spells that Shadows, etc cast.

**Comment by jkachhad** [comment]
Spells can have intensities, similar to say Magic Missile. In order give thief more power in later levels, we gave them a 1x1 Darkness spell.  You can specify the intensity like so:
```
shadow.Spells = new CreatureSpellCollection()
{
        new CreatureSpell<DarknessSpell>(
            skillLevel: 8, cost: 4, intensity: 2,
            mantra: SpellHelper.GenerateMantra(), instantCast: false),
};
```
The `intensity` argument allows this.
