### ISSUE TITLE
Lair Monsters focusing on one target

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#553]
Drake and Giant focus one target and never swap. Suspect other lair crits might have this issue as well but haven't tested with multiple players. Not sure if mechanic is available yet but it makes them super easy to kill as they won't swap to squishy targets ever.

**Comment by jkachhad** [comment]
Use `CombatantChangeInterval` property. Example: `drake.CombatantChangeInterval = TimeSpan.FromSeconds(30.0)`
