### ISSUE TITLE
Missing: Ability to see other users in conference.

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#559]
[Reported by surf]

**Comment by surfotato** [comment]
![image](https://user-images.githubusercontent.com/85204505/124506641-f459a480-dd80-11eb-9925-a23a5a77895d.png)

**Comment by jkachhad** [comment]
This is correct behavior. There is 1 use in the conference room, but no one playing the game. We need to implement a users command that shows who is in the room with you.
