### ISSUE TITLE
Axe quest NPCs / Items not defined yet

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#565]
- [x] Not sure on kwolf spawn.
- [ ] Martial Artist - unsure of context. Maybe fine.
- [x] Rockworm = Sandwyrm?
- [ ] Lizard spell syntax - copied salamander but not 100% on variables.
- [x] Giant = ElderTroll type atm. Stats wildly unsure
- [x] Goose = dog atm.
- [x] Drake = dragon model
- [x] Mama needs HeavySilver immunity variable needed to be added.
- [x] no Statue model available in menu.
- [x] No value for Vulcan.
- [x] No value for Silvermoon
- [ ] Not sure on MA trainers.
- [x] No lockpick town spawns.
- [ ] Treasure needs full rework.

**Comment by jkachhad** [comment]
- Looked through king wolf and gave him magic immunity, he also had 50% magic protection with weakness to IS and Death. 
- Added ObsidianEgg and updated Vulcan to craft greataxe.

**Comment by jkachhad** [comment]
- Implemented type specific weaknesses and immunities.
