### ISSUE TITLE
Strength / Presumably Dexterity adds from items not showing

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#570]
Character stats window doesn't show strength adds when you put on +strength items. (Damage value does reflect it though)

**Comment by SewerCzar** [comment]
It's also worth noting that strength does increase damage but not attack values at all? Not sure if intended

![levelglows](https://user-images.githubusercontent.com/86573170/124607690-15330000-de3c-11eb-948f-08e2c2b8cb5c.PNG)
![levelnoglows](https://user-images.githubusercontent.com/86573170/124607705-16fcc380-de3c-11eb-88d9-660e2cc3fb09.PNG)

**Comment by Tawnos-LOK** [comment]
Merging with #661 on the character stat note.  The other note about AR is working as intended per Lux - Adds don't add AR
