### ISSUE TITLE
Leveling up adds no attack value

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#571]
When leveling a fighter from 1 (or 3?) to 24 I noticed I gained no values to my attack adds:

![level1stats](https://user-images.githubusercontent.com/86573170/124607891-43184480-de3c-11eb-88c3-42a8786153a5.PNG)
![level24stats](https://user-images.githubusercontent.com/86573170/124607900-44e20800-de3c-11eb-8423-6e82749a5b33.PNG)

**Comment by Tawnos-LOK** [comment]
Along the lines of  Leo discussion with Lux - Confirmed that adds to not affect AR as intended
