### ISSUE TITLE
phantasm don't disappear

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#582]
summoned phantasms don't seem to have a timeout counter so you can leave them all over and they don't disappear untill summoner cast spell again   if you leave them in one land and portal to another they will remain even when casted in new land for example can cast 3 in axe leave to oak and cast 3 more and when returning to axe the first 3 will still be there and active for the player [Reported by bulsie]

**Comment by jkachhad** [comment]
Do you have information on how quickly they should dispel? I've set it to 10 minutes default at all skill levels.

**Comment by Chilly021** [comment]
Should be fixed.

**Comment by Chilly021** [comment]
Re-reading there is a little more context.

**Comment by sproatba** [comment]
This scales with skill on lands, I want to say og was 2 minutes per skill level.  Lands shorted that a bit, I think they did 2 minutes per skill - 5 or something.
