### ISSUE TITLE
Salamanders

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#59]
Salamander scales to no offer fire resistance it seems. Noticed no difference with or without while standing in their fire.

They can also be fizzled now. Dont remember that happening earlier on.. I was fizzling 2 in -4.

**Comment by jkachhad** [comment]
I tested with the recent patch, seemed to provide fire resistance.  I used Fireball with intensity of 1.

[Luxx 2019-05-31 22-30-45.zip](https://github.com/jkachhad/Stormhalter/files/3243332/Luxx.2019-05-31.22-30-45.zip)

**Comment by SlysterLOK** [comment]
Let me check again. I did not use a player spell but salamander fire to test before.

**Comment by jkachhad** [comment]
Since there are other issues with Fire Protection, I'll close this one. The fizzle issue should be fixed as of v0.19
