### ISSUE TITLE
Monsters with Crossbows (Such as Doom Orc) Don't have it pre-knocked

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#591]
I just took out the entire doom orc pack with 0 threat. I dont feel like OG was like this but possibly was. Replay available: send a PM

**Comment by jkachhad** [comment]
Typically crossbows un-knock when moving. Did this not occur in OG?

**Comment by SewerCzar** [comment]
In OG crossbows would stay knocked, other bows wouldn't. And mobs knocked crossbows as they ran around. The Doombow for thief is a good example: you can knock it, belt it, run with it, and then shoot it right after running. Without that functionality the orcs just run back and forth staring at you in the doom orc lair, dodging not needed. I don't recall it being that way in OG but could be incorrect.

**Comment by SewerCzar** [comment]
So I did some research and I discovered: They'd run with it pre-knocked and shoot at thieves from 1 hex away. If they missed they would run in and out like other archer mobs without knocking again but if they hit you they would run and knock again if you were still visible
