### ISSUE TITLE
Can't belt other people's tied weapons

### ISSUE THREAD

**Issue by SewerCzar** [jkachhad/Stormhalter#592]
In OG you couldn't put them in hands but you could belt them for dpile recovery. It doesn't "leap out of my hands" it just goes back onto the floor when I try to pick up another players BBS, etc.

**Comment by jkachhad** [comment]
I was able to belt a doom orc cross bow off a thief on another wizard. Test from hands, from floor, to hands, to sack, and to sack button.

Could you check again and verify it's going to the right slot? Certain large items can't be belted in the small slots.

**Comment by SewerCzar** [comment]
This was either fixed at some point or I'd tried to put a BBS into an inappropriate spot. Could have been a mistake but definitely feels resolved now. I will close this!
