### ISSUE TITLE
Tanned Armor

### ISSUE THREAD

**Issue by SlysterLOK** [jkachhad/Stormhalter#60]
So far I have tested Wyvern Armor and Salamander Armor. Neither offer much different ( if any ) protection than the starting leather armor. Even in -1 armor blocks very rarely happen.

**Comment by jkachhad** [comment]
I tested this, went from 150 to 110 with the scales on, 150 to less than 50 without scales. Would you mind retesting? I used Fireball of 1 intensity to test.

**Comment by jkachhad** [comment]
Leather armor does not offer much protection against piercing weapons, making those rapier skeletons a little more dangerous on -1. Both Wyvern and Salamander scales should offer protection against them. The Salamander scales offer 5 points of fire protection.

**Comment by jkachhad** [comment]
I had an opportunity to look at defense and damage reduction provided by armors. I'm uncertain about the OG mechanics, but NG mechanics only offered damage reduction above certain threshold values. For example, Dragon Scales did not provide any damage reduction, but Ice Dragon Scales do.

In regards to blocking, there are categories for attacks, such as piercing, slashing, and bashing. Armor provide protections in these categories (and others) against the attack types. If the attack is slashing, but the armor does not provide slashing protection, it's not beneficial. That said, you would except Troll (Trog) vest to provide twice the protection in all categories compared to Salamander Scales. Where the latter benefits is providing fire protection.
