### ISSUE TITLE
Sometimes shooting a nocked crossbow misfires

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#604]
I've had this happen 3-4 times. I jumpkick an enemy after using my nocked crossbow to bring up a targeting reticle. In the attached replay, this occurs around the 3:30 mark when I try to shoot a wolf. [Reported by korazail]

**Comment by yarrim** [comment]
[Korlanis 2021-08-06 11-18-58.zip](https://github.com/jkachhad/Stormhalter/files/6946488/Korlanis.2021-08-06.11-18-58.zip)
