### ISSUE TITLE
lock pick town/skeletons/oak

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#616]
the recall seller in lockpicktown doesn't sell recalls also there is no weapon trainer in the lockpick trainer area. 

skeletons on kes-1 u get skill for hitting them with weapons that are ineffective. 

oakvael wiz trainer for some reason is located on the counter nw of recall seller.. and everytime i go into doom.orc lair and move 2 west from portal my game closes [Report by Kuruptlord]

**Comment by zrikzlok** [comment]
Axe - fixed recall seller and added weapon trainer to training area
Oak - moved wiz trainer to appropriate spot!
I Can't help with ineffective gains
