### ISSUE TITLE
giant lair portal

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#624]
my game closes everytime i portal into giants lair it also doesn't need an axe to get inside and the portal back out doesn't work
 [Report by Kuruptlord]

**Comment by zrikzlok** [comment]
added teleport out and fixed secret doors

**Comment by jkachhad** [comment]
In the future, you can add a comment in your PRs like: [Fixes/Closes/Resolves] issue #xxx  
It will automatically close the issue when the PR is merged.
