### ISSUE TITLE
Climb Downs and Falling

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#633]
Some areas like the climb down to Kes -3 from the surface and -1 to Trog level have you fall when double clicking instead of climbing. [Report by Slyster]

**Comment by jkachhad** [comment]
I think this the default action for shafts?

**Comment by zrikzlok** [comment]
I believe that is accurate, if you double clicked in OG you fell down and took damage.. it was just typically not noticed due to most people having FF boots. when doing naked runs had to do climb down if I recall
