### ISSUE TITLE
Darkness - Oak -1 and Oak -2

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#643]
Oak -1 and Oak -2 have a 2 view range when it is dark outside. This also impacts the mobs ability to see characters in the dungeon beyond the 2 view radius. [Report by BruceWee]

**Comment by SewerCzar** [comment]
No worries but I believe this is a duplicate report on this issue: https://github.com/jkachhad/Stormhalter/issues/543

**Comment by Tawnos-LOK** [comment]
Merging similar issues
