### ISSUE TITLE
macro errors generate client crash with no message

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#644]
I created a character specific macro for 'cu = climb up' not realizing the salad already existed. Could not log into world as that character afterwards until I removed the macro definition. Client would crash without any error message. Expected behavior would be an error stating: macro $whatever cannot override existing command.- or allow the override. [Reported by korazail]

**Comment by yarrim** [comment]
Sigh... Salad=command. Phone autocorrect.
