### ISSUE TITLE
hiddenteleportcomponent mantra

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#645]
allow a hiddenteleportcomponent to be activated via mantra [Suggested by zrikz]

**Comment by zrikzlok** [comment]
also need a check box for a teleporter to strip all gear and leave it on the ground

**Comment by jkachhad** [comment]
SpeechTeleporter has been added.  As I'm uncertain on the fate of the Underworld for this iteration, I'll refrain from adding a teleporter that strips players, to prevent incorrect usage.  Closing the issue for now.
