### ISSUE TITLE
Character Creation Attributes

### ISSUE THREAD

**Issue by jkachhad** [jkachhad/Stormhalter#65]
Players are reporting that max attributes should be different than what is currently implemented. The current implementation was taken from the following in LOK Kompanion:
![image](https://user-images.githubusercontent.com/1934897/58646960-89516000-82d4-11e9-8ac2-b0f160e5a8cc.png)

Please let me know if you come across another source that has it different, Lands of Kesmai or the various help files.

**Comment by jcross** [comment]
I assume that's from the HTML conversion of the Kompanion. That's not actually the latest and most complete one that was created. It's likely that the Fighter Constitution was a bug that was fixed on the game or a typo in that version of the Kompanion. I've attached a ZIP with other versions of the Kompanion. v1.1a is the latest, as far as I know. And it shows 18 Constitution for Fighters.
[LoK_Kompanions.zip](https://github.com/jkachhad/Stormhalter/files/3238456/LoK_Kompanions.zip)

**Comment by SlysterLOK** [comment]
The fighter Con has to be a typo considering the rest of the classes can be 18 Con.

My personal opinion is for Thieves - 18 INT - 18 Char Max

**Comment by jkachhad** [comment]
Something to notice, especially if fighter Con is max 18 at creation, that every class has two stats that can be maxed. One is Con, the other is the primary stat. With thieves at 18 Int, that would give them 3 stats that can be max.

**Comment by SlysterLOK** [comment]
Would that in the end truly matter? Thieves have to go through a lot anyway lol. Your call.

**Comment by jkachhad** [comment]
I came across another Kompanion that I believe was edited in the context of Lands of Kes.
[Kompanion_v2.3.1.zip](https://github.com/jkachhad/Stormhalter/files/3241220/Kompanion_v2.3.1.zip)

I'll be changing the attributes starting to as below:
![image](https://user-images.githubusercontent.com/1934897/58705503-6e86f600-837d-11e9-8e51-6517ffdc874c.png)

You'll be happy to see thieves did start with 18 int on Lands of Kes. :)
