### ISSUE TITLE
Dull Opals not disintegrating 

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#650]
Dull Opals no longer disappear when mobs pick them up. They should. Otherwise after a few seconds their packs are full and they move away. Makes the ability not useful enough [Report by Slyster]

**Comment by zrikzlok** [comment]
ah yeah I thought they were supposed to disintegrate, been hunting in -3 and see a billion of them when I kill mobs

**Comment by jkachhad** [comment]
I have them marked as `ITreasure` to have monsters pick them up. Disintegrate does not work on treasure. I added a CanDisintegrate property to items and is implemented as follows:

```
ItemEntity.CanDisintegrate => (item is not ITreasure);
Corpse.CanDisintegrate => false
HoodwinkOpal.CanDisintegrate = true
```
