### ISSUE TITLE
Shop items should disappear when bought

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#659]
After purchasing an item from the shop it should drop off the list. At least the rare items such as F/I Rings [Reported by Slyster]

**Comment by jkachhad** [comment]
For `StockEntry`, added a `AllowRestock` parameter to prevent restocking of items.
```
new StockEntry("vermeil ring", () => new VermeilRing(), (int)(300 * merchantUpsell), Utility.RandomBetween(1, 2), null, allowRestock: false),
```
