### ISSUE TITLE
Death bug, negative constitution and 0 Stam

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#666]
As I was going to reroll my character, I had him die ~1000 times jumping from oak and having priest death loop me just to see if there were any high death count bugs. I'm not sure if intended but CON can go negative, mine is currently -1050 or so, also i appear to actually have 0 stam. Thought I'd mention in case this is not intentional. [Report by Tygre]

**Comment by zrikzlok** [comment]
hah, well, good testing, I suspect this is not intended.

**Comment by Tawnos-LOK** [comment]
Closing for now with the phasing out of the death penalty system.  When the next version gets implemented, we'll retest these sorts of items.
