### ISSUE TITLE
Slate counters - can't interact with if they are south of you

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#668]
Don't appear to be able to interact with slate counters if you are noth of them you get "you are unable to look from here"  [Report by Zierz]

**Comment by Chilly021** [comment]
@zrikzlok  is there a counter we can test this with still?

**Comment by zrikzlok** [comment]
unsure, I changed towns around to make them work. I'll make a small spot in bloodlands surface to throw some things in later today, if you notice more similar to this and the static stairs @me

**Comment by Chilly021** [comment]
I'll have to go zone by zone. It's been a hot minute since I went to Black Burrow and tested there.

**Comment by zrikzlok** [comment]
I think I noticed bricks right away when he first made the zone and he moved his counters to fix the issue.
