### ISSUE TITLE
Slippery bottles

### ISSUE THREAD

**Issue by dedmist** [jkachhad/Stormhalter#67]
I and another player were drinking bottles directly from the ground.  After a while of this, I was trying to pick up an intelligence potion and it would not drag onto my character page or icon, it would revert back to the ground.  At some point, I thought it was an issue with the ground refresh, but I tried a few times when the other player wasn't doing anything and it still happened.  Eventually, this crashed the client, having taken no actual actions.

**Comment by dedmist** [comment]
I asked Doomie and he experienced the picking up bug as well, but didn't get a client crash.  We were both picking up bottles directly to the paper doll.

**Comment by jkachhad** [comment]
I wonder if you both of you picked up and drank the bottle at the same time.

**Comment by SlysterLOK** [comment]
I had the same issue this morning and was alone. I had to log out and back in to pick up a second DP.
