### ISSUE TITLE
stairs and static components on same hex

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#670]
if stairs have a static component on the same hex it appears to break the stairs. Can still type up/down, but it just sits there [Reported by zrikz]

**Comment by Chilly021** [comment]
@zrikzlok  is this still an issue?

**Comment by zrikzlok** [comment]
hmm I'm not sure. this may have been related to a bug where we thought it was a static component but it was actually dealing with tiles at coordinates with a x or y = 0. I can add a random stair case in bloodlands to test.

**Comment by Chilly021** [comment]
I think we fixed this. It was a combination of things. Two different areas either had same height OR at one point the stairs in the components xml did not have the correct action. We can re-open this if this is an issue again for sure!
