### ISSUE TITLE
Weapon BaseArmorBonus does not apply to player

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#677]
BBS has a BaseArmorBonus of 3 while SGA has a BaseArmorBonus of 1, yet defense rating in debug combat is the same using either. [Reported by HealthySnack]

**Comment by trlook** [comment]
It seems this bonus is applying only to when being attacked by a weapon. Being attacked by a creature not wielding a weapon, such as an animal or dragon, does not gain bonus. Hence, weapon choice won't matter defensively for most lairs.

I will do some more tests to see if it works with hand skill against monsters, can I attack an orc defender with my hands vs weapons and deal with less defense?

**Comment by Leolus** [comment]
Results in about -100 DR when using maces. It appears the DR bonus is 1 per 5% meaning this costs about 5 skill levels worth of blocking if that's linear.

**Comment by jkachhad** [comment]
Resolved on the next update.
