### ISSUE TITLE
Returning Axes

### ISSUE THREAD

**Issue by jkachhad** [jkachhad/Stormhalter#71]
![159](https://user-images.githubusercontent.com/1934897/58669485-617cef00-830a-11e9-951c-e4de0c808987.png)
![077](https://user-images.githubusercontent.com/1934897/58669486-617cef00-830a-11e9-95cd-7b2e07511f89.png)

Thoughts on any differences? The bottom one is the Returning Axe you would normally get through the quest. I don't ever recall seeing the first.

**Comment by SlysterLOK** [comment]
I do not remember the first either. I know the OG had plenty of unused art either just being left in the files because the other version was better or upcoming content that never came out.

**Comment by mtweldon** [comment]
could provide an avenue for Raxe2 down the road, or whenever the axe has a modified stat (damage +10%) or what have you

**Comment by SlysterLOK** [comment]
I am thinking of something more than just a simple damage increase.. I am thinking multi target or something. Extra damage is great but to simple.
