### ISSUE TITLE
weak str rings bugged, give +3 str

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#725]
also weird behavior with how putting on equipmenet adjust stats. [Reported by HealthySnack]

**Comment by trlook** [comment]
> 
> 
> also weird behavior with how putting on equipmenet adjust stats. [Reported by HealthySnack]

Okay, so from further testing, no damage bonuses up to 18 character sheet strength.  Adding +6 strength also gives no bonus damage.  After that, get bonus damage for each +3 up until 36 strength:

- 18 str (no dmg bonus)
- 24 str (no dmg bonus)
- 27 str (dmg bonus)
- 30 str (dmg bonus)
- 33 str (dmg bonus)
- 36 str (dmg bonus) (cap)

For similar behavior to dex, a damage bonus should be awarded at both 18 and 24 strength. However, not sure if this is the intended behavior or not.
