### ISSUE TITLE
Potential Server Crash with Poison Cloud

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#727]
So while spamming Poison Cloud, after about 30 minutes or so with multiple zoo respawns the server will randomly crash after Poison Cloud collides with a bunch of crits. Not sure if this is linked to visibility, or the mobs being 'blinded' or the massive amounts of gold/items they could be carrying as they die. But this has happened about 3 or 4 times today. It's a bit hard to force a replication and seems to randomly happen. [Reported by Victor]

**Comment by jkachhad** [comment]
I threw some PCs around UK, didn't seem to have any issues. Could have been related to something else, possibly just a client crash and not server.
