### ISSUE TITLE
Creatures not getting weapon/shield BaseArmorBonus vs Hand Attacks

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#730]
related to the player issue, creatures don't get weapon/shield BaseArmorBonus if the player isn't attacking with a weapon type, i.e. an attack vs. a monster with shield/weapons is easier to land with hand than a weapon due to seeing less defense. [Reported by HealthySnack]

**Comment by jkachhad** [comment]
Resolved on the next update.
