### ISSUE TITLE
halberds trigger extra defenses on target

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#739]
attacking with halberd causes the defender to gain double the basearmorbonus of their weilded items, perhaps this is because it has both slashing and bashing properties? [Reported by HealthySnack]

**Comment by trlook** [comment]
Needs to be fixed in the Armor.cs class. The implementation of the fix requires design choices.

**Comment by sproatba** [comment]
@Chilly021 I think this can be closed
