### ISSUE TITLE
Spell skill gain is funky

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#761]
Spells that instantly appear to give a killed spell skill bonus, but spells that kill things non instantly, aka WW, poison cloud, seem to give significantly less skill when they kill things. Is the spell only checking for killed gain bonus if it immediately kills? [Reported by SewerCzar]

**Comment by Wirednuke83** [comment]
I've seen this on my wizard as well. Also notice that buffs don't seem to give magic skill gain if you are wearing an item that carries that effect.

**Comment by Tawnos-LOK** [comment]
This was adjusted in a patch.
