### ISSUE TITLE
Bug - targetting through walls

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#776]
I used create portal to open a wall.  A wraith targetted me.  When the wall closed, the wraith still casted more death spells at me for multiple rounds, evne though I could no longer see him or "hear" him via chat.   [Report by XeroX]

**Comment by jkachhad** [comment]
I'm unable to replicate this, do you where it occurred? Did you have a portal spell in between, possibly any replays?

**Comment by Chilly021** [comment]
This seems not to be a bug.
