### ISSUE TITLE
Mob/Dark interaction

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#777]
I was standing in darkness and a wraith could not see me.  As soon as I hit him with a spell, he was then able to see me.  Seems weird that something like attacking a mob would essentially give them nightvision, not sure if functioning as intended. [Report by XeroX]

**Comment by jkachhad** [comment]
Are you certain he was not able to see you prior? I was not able to reproduce the cases with Wraith on -3. Are you certain they don't have night vision?

**Comment by jkachhad** [comment]
I believe this may have been related to a similar issue where OL could see you on a specific hex outside of his lair.
