### ISSUE TITLE
Coins in sack

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#781]
Coins should not be able to be placed on any slot of the bottom row in the sack. Traditionally, it has always only been at the very bottom left.

Curerntly, you are able to move these coins to ANY slot in the sack.

Not an issue pursay, just a suggestion based on original game mechanics. [Report by Taelamar]

**Comment by SlysterLOK** [comment]
Known and a convenience. Just like the whole bottom row being usable now. In OG only coin in the bottom row.
