### ISSUE TITLE
Vision issues with Perception and dark hexes

### ISSUE THREAD

**Issue by yarrim** [jkachhad/Stormhalter#786]
Perception seems to provide a weak Night Vision, I can see into darked hexes with some caveats:

I can only see into a dark hex if it is next to a wall, and I can see past dark hexes even if I can't see into them:
![image](https://user-images.githubusercontent.com/11442233/131677858-e3422349-797b-41e5-8e8e-bc1751aab65a.png)
![image](https://user-images.githubusercontent.com/11442233/131677772-c8d921e1-c9f2-4676-8c6b-556bf8cbdbce.png)

I cannot fight in a dark hex if I don't have NV from another source, * doesn't do anything and I get the message 'I can't tell who you mean' if I double click a mob I can see
![image](https://user-images.githubusercontent.com/11442233/131678139-db45342c-1b5b-412d-9955-3ec2f5beb82b.png)

The latter may be intentional. the former is probably not.

**Comment by jkachhad** [comment]
Resolved on next update.
