### ISSUE TITLE
Yasnaki Secret Door 24,16

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#790]
Secret door Closed position is a right angle SW corner piece, should be flat horizontal, unless this is an OG thing i don't remember. [Report by Amedi]

**Comment by rutir** [comment]
Meant [24, 19] not 16, 16 is the area ID (Yasnaki)

**Comment by yarrim** [comment]
Resolved in #1062

**Comment by Tawnos-LOK** [comment]
Resolved per note above
