### ISSUE TITLE
Wandering mobs can get stuck, pathing issues

### ISSUE THREAD

**Issue by yarrim** [jkachhad/Stormhalter#798]
Xero found the behavior in the attached replay.
Mobs seem to be able to get stuck in places where their wander AI will not path out of a certain region.

attached zip has two replays, but the behavior here can be replicated.
![image](https://user-images.githubusercontent.com/11442233/131933838-550052e0-ec6e-47c3-9f60-9a29b2ec7568.png)

The mobs in the screenshot would only move east and west.
Mobs entering the 'closet' to the west of here, will not wander out and mobs that were not chasing me that moved into the bottom set of tiles would never leave them, just pacing back and forth, but leaving the screen to the east.

in Xero's replay, you can see the closet. in my replay, at about the one minute mark, I catch two orcs in the East\West trap.

[wanderAi.zip](https://github.com/jkachhad/Stormhalter/files/7102623/wanderAi.zip)

I don't see anything wrong with the tiles or components in this area. The spawner for these mobs is a region spawner with one big inclusion and two exclusions, but the exclusions don't appear to impact these tiles, as mobs will wander INTO the "trap".

This may be related to a reported place in Oak at 9,-2 [235] (serpent sea) where mobs would not naturally path south and find a hidden thief. That spawner has no exclusions.

**Comment by yarrim** [comment]
This issue still exists. a fresh replay of the original area in kes -2. as well as a recent spot in oak serpent sea:
[[kes-2]MobTrap.zip](https://github.com/jkachhad/Stormhalter/files/7653137/kes-2.MobTrap.zip)
[odd_mob_behavior.zip](https://github.com/jkachhad/Stormhalter/files/7653138/odd_mob_behavior.zip)

**Comment by yarrim** [comment]
I just reconfirmed the issue is still present in v0.89.2. The Kes -2 stairs near Thief guild basement is easy to reach and demo this behavior. Any mob that enters the South-most row of hexes never paths north again unless chasing another entity. A hidden thief can watch this play out.

**Comment by jkachhad** [comment]
Had time to research this. The exact spot you described has this issue.  There is an algorithm that splits up a rectangle into multiple rectangle when it includes an "exclusion" rectangle. I'm not sure why the split occurs this way.

Here is one of the generated rectangles from Kesmai -2
```
[1] = Rectangle2D
 Area = {int} 34
 Bottom = {int} 39
 End = {Point2D} (33, 39, [12])
 Height = {int} 1
 Left = {int} 0
 Region = {int} 12
 Right = {int} 33
 Start = {Point2D} (0, 39, [12])
 Top = {int} 39
 Width = {int} 34
```

Here is the algorithm where I think the issue may be occurring, I'll check further tomorrow.

```
foreach (var exclusion in exclusions)
{
	var updatedInclusions = new List<Rectangle2D>();

	foreach (var inclusion in inclusions)
	{
		if (inclusion.Intersects(exclusion))
		{
			if (exclusion.Top > inclusion.Top) /* Top rectangle. */
			{
				updatedInclusions.Add(new Rectangle2D(inclusion.Left, inclusion.Top, inclusion.Width,
					exclusion.Top - inclusion.Top - 1, inclusion.Region));
			}

			if (exclusion.Bottom < inclusion.Bottom) /* Bottom Rectangle */
			{
				updatedInclusions.Add(new Rectangle2D(inclusion.Left, exclusion.Bottom + 1, inclusion.Width,
					inclusion.Bottom - exclusion.Bottom - 1, inclusion.Region));
			}

			var top = Math.Max(exclusion.Top, inclusion.Top);
			var bottom = Math.Min(exclusion.Bottom, inclusion.Bottom);
			var left = Math.Max(exclusion.Left, inclusion.Left);
			var right = Math.Min(exclusion.Right, inclusion.Right);
			
			if (exclusion.Left > inclusion.Left) /* Left Rectangle */
			{
				updatedInclusions.Add(new Rectangle2D(inclusion.Left, top, 
					left - inclusion.Left - 1, bottom - top, inclusion.Region)); /* Height here may not be correct */
			}

			if (exclusion.Right < inclusion.Right)
			{
				updatedInclusions.Add(new Rectangle2D(right + 1, top, 
					inclusion.Right - right - 1, bottom - top, inclusion.Region)); /* Height here may not be correct */
			}
		}
		else
		{
			updatedInclusions.Add(inclusion);
		}
	}

	inclusions = updatedInclusions.ToArray();
}
```

**Comment by trlook** [comment]
So, I think I figured it out. In bottom rectangle, there is not enough height, but the top left corner of the rectangle is fine, so the -1 padding in the 3rd arg should be removed

`
			if (exclusion.Bottom < inclusion.Bottom) /* Bottom Rectangle */
			{
				updatedInclusions.Add(new Rectangle2D(inclusion.Left, exclusion.Bottom + 1, inclusion.Width,
					inclusion.Bottom - exclusion.Bottom, inclusion.Region));
			}
`

The widths of the left and right Rectangles need to be fixed as well

`
			if (exclusion.Left > inclusion.Left) /* Left Rectangle */
			{
				updatedInclusions.Add(new Rectangle2D(inclusion.Left, top, 
					left - inclusion.Left, bottom - top, inclusion.Region));
			}

			if (exclusion.Right < inclusion.Right)
			{
				updatedInclusions.Add(new Rectangle2D(right + 1, top, 
					inclusion.Right - right, bottom - top, inclusion.Region));
			}
`

Try that and see if the rectangles are all correct

**Comment by jkachhad** [comment]
I don't think what i have implemented is well suited for breaking up rectangles. It needs to be recursive as the inclusion rectangles are broken down. I'll have to implement something else or research more.

**Comment by trlook** [comment]
It should be fine because it updates the inclusion list before starting the next exclusion check?

**Comment by trlook** [comment]
As a follow up to my above comment, the algorithms outer loop is over exclusions, it then loops through the inclusions breaking them up each time an exclusion overlaps an inclusion. Since the inclusion list is updated before the next exclusion in the loop, and a correctly broken up inclusion shouldn't overlap a previously tested exclusion, this algorithm should work. I think my above proposed changes fix the inclusion generation issues (boxes were sometimes short in both X and Y).

**Comment by jkachhad** [comment]
Here is an implementation that I think works: https://dotnetfiddle.net/WwHFyj
I may have to refactor how I construct the rectangle, doing it by x1, y1, x2, y2, rather than x, y, width, height -- this might be causing some confusion. I also need to rework how I use width, or alternatively Right/Bottom coordinates.

**Comment by jkachhad** [comment]
```
if (exclusion.Top > inclusion.Top) /* Top rectangle. */
{
	updatedInclusions.Add(new Rectangle2D(inclusion.Left, inclusion.Top, inclusion.Width,
		exclusion.Top - inclusion.Top, inclusion.Region));
}

if (exclusion.Bottom < inclusion.Bottom) /* Bottom Rectangle */
{
	updatedInclusions.Add(new Rectangle2D(inclusion.Left, exclusion.Bottom + 1, inclusion.Width,
		inclusion.Bottom - exclusion.Bottom, inclusion.Region));
}

var top = Math.Max(exclusion.Top, inclusion.Top);
var bottom = Math.Min(exclusion.Bottom, inclusion.Bottom);
var left = Math.Max(exclusion.Left, inclusion.Left);
var right = Math.Min(exclusion.Right, inclusion.Right);

if (exclusion.Left > inclusion.Left) /* Left Rectangle */
{
	updatedInclusions.Add(new Rectangle2D(inclusion.Left, top, 
		left - inclusion.Left, bottom - top + 1, inclusion.Region)); /* Height here may not be correct */
}

if (exclusion.Right < inclusion.Right)
{
	updatedInclusions.Add(new Rectangle2D(right + 1, top, 
		inclusion.Right - right, bottom - top + 1, inclusion.Region)); /* Height here may not be correct */
}
						```
