### ISSUE TITLE
Additional damage taken from Mama

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#819]
Mana swung once and combat log showed 100 damage. Took more than 150 damage from the swing. Submitting replay to replay channel. Issue occured at 11:53 in replay. [Report by Leokn]

**Comment by Leolus** [comment]
Replay added to replay channel with comment: **Replay of issue 819: https://github.com/jkachhad/Stormhalter/issues/819**

**Comment by sproatba** [comment]
replay crashes the current client, closing this one for now.  Assuming it was a wall slam adding damage maybe?
