### ISSUE TITLE
Eternal "busy" circle -- CANNOT PLAY CHARACTER

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#826]
I summoned a rat to demolish a wall and was attacked by an orc.  Upon typing "rest" and returning to my thief, I could perform no actions.  I have an eternal "busy' circle.  I relogged, reopened client, faceted, etc, and still have an eternal busy circle.  I can play other characters fine, but not my thief. [Report by Xero]

**Comment by Chilly021** [comment]
Need steps to see if this still an issue. This was created in September. We can reopen this if we see this same issue again.
