### ISSUE TITLE
Jumpkick stamina use

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#83]
jumpkick doesn't currently appear to use stamina

**Comment by jkachhad** [comment]
Stamina loss should be occurring based on your encumbrance and the following factors:
1. Number of steps (jump-kicking uses 3 regardless of actual distance)
3. If you suffered a sprain (based on effective skill level, skill - hindrance) during a jumpkick.
4. If you were strained (dense forest) while walking.
