### ISSUE TITLE
Willpower

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#85]
Willpower used to go up to 18, seems maxed out at 16.

**Comment by jkachhad** [comment]
![image](https://user-images.githubusercontent.com/1934897/58822481-9f795c00-8605-11e9-804f-4cd4d51b5416.png)

Should be resolved for all attributes and maximum per class. There are now 3 limits, the inborn min/max, and live max.  You will have to remake your character for the new limits.
