### ISSUE TITLE
Right clicking on rings

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#850]
If you right click on a weak shield ring, it doesnt tell you anything.  If you right click on a medium shield ring, it tells you it is a medium shield ring.  Basically, the medium gets identified for free simply by clicking on it. [Report by Xiro]

**Comment by jkachhad** [comment]
I tested all three rings. They appear to show their description properly when identified using a vermeil ring.  Did you identify them prior, or just right click?  Once an item is identified, it will show it's magical properties.
