### ISSUE TITLE
Balance for Casters

### ISSUE THREAD

**Issue by Chilly021** [jkachhad/Stormhalter#858]
Casters have no place in end game yet. Either OL staff will have to be like the olden days (nearly non impassible) or spell damage needs to be amplified to a balancing point. 

1) Glass Cannons
OR
2) Best Defense in Game

**Comment by Wirednuke83** [comment]
> Casters have no place in end game yet. Either OL staff will have to be like the olden days (nearly non impassible) or spell damage needs to be amplified to a balancing point.
> 
> 1. Glass Cannons
>    OR
> 2. Best Defense in Game

I think spell damage is a little low right now. I passed some replays to lux from Lands as a reference. I know in Lands and original Gamestorm, Ice speare was 14 damage per mana, and death was 10 damage per mana. Fire and Ice storm need to be tweaked up a bit. 

I think wizards are ok if they get their damage raised. They have the ability to manipulate the environment through illusions to survive encounters. 

Thaums need work though, they either need a boost to blocking... a boost to djinn/efreet defense/hp or a new line of spells that provide some kind of rune/shielding effect. 

I was planning on opening a separate issue for thaum balance.

**Comment by Chilly021** [comment]
I'm leaning towards upping Djinns Defense and immunities for Thaums.  I can get around okay, but endlessly recasting djinns due to their inability to handle even one pack of crits almost. I can hack/spell cast whatever is on them to death but that's leaves me exposed. With 2 packs on them they are gone in seconds.

Also either add a new spell for damage output similar to icespear or up Death to do quite a bit more as you said. I would love "smite" or something along those lines. 

I have not played a wizard yet in Stormhalter, so I default to what you and others have said.

**Comment by Chilly021** [comment]
I tweaked the immunities and defense more than once. I barely touched the HP. So it acts as a "pseudo" scaling for thaums. It would honestly be best though for these to scale on player level / magic level. 

For Wizards, there are a bit too many issues to worry about here. If we up damage in general, resists are not easily able to attain early for Skulls / Armor. You can cast f/i but if you up fire ball and icestorm, it affects early game by quite a bit, since the ticks seem to stack. Maybe creature vulnerability can be put in for negative resists? This was something that Diablo did to combat certain zones/areas and to scale.
