### ISSUE TITLE
Slipping when climbing UP ( slip chance 0 )

### ISSUE THREAD

**Issue by yarrim** [jkachhad/Stormhalter#860]
Issue occurs at about 48 seconds, or 4/5ths through the attached replay.
I fall negative feet when I slip on the rope up to kes lockers.
[Salemine 2021-09-11 21-13-23.zip](https://github.com/jkachhad/Stormhalter/files/7148819/Salemine.2021-09-11.21-13-23.zip)

**Comment by yarrim** [comment]
Tenroo had a fatal slip when climbing up to Oak town, The rope here has a slip chance of 0 and seems like one that should never slip.
This occurs at the very end of the attached repla
[Tenrou_2021-09-21_21-18-14.zip](https://github.com/jkachhad/Stormhalter/files/7207166/Tenrou_2021-09-21_21-18-14.zip)
y.

**Comment by Chilly021** [comment]
This seems to be happening to a few HC people here.

**Comment by jkachhad** [comment]
There is a base slip chance with each character.  The rope adds to the slip chance.
