### ISSUE TITLE
Perception doesn't work on teleport hexes

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#867]
Perception cast will fail if casted onto a teleport hex (Stairs, portals, etc) [Reported by Wirednuke]

**Comment by jkachhad** [comment]
I had no issues using perception on a hex. Is it a particular set of stairs?

**Comment by Wirednuke83** [comment]
> I had no issues using perception on a hex. Is it a particular set of stairs?

If you cast perception on a stairs hex while you are on it (for the debuff). It fails.

**Comment by jkachhad** [comment]
Do you mean Shadowstep?

**Comment by Wirednuke83** [comment]
Yes sorry lol

**Comment by Wirednuke83** [comment]
Here is a replay. I changed the file extension to .txt so it would upload here. 


[Bagogold 2021-09-24 11-37-33.txt](https://github.com/jkachhad/Stormhalter/files/7226888/Bagogold.2021-09-24.11-37-33.txt)

**Comment by jkachhad** [comment]
Resolved in the next patch. You can no longer Shadowstep on your own hex, but can do so towards staircases.
