### ISSUE TITLE
Gaining skill with Dagger on skeletons

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#875]
Dont know if your suppost to gain skill with dagger on skellys but ya do. [Report by Grimfate]

**Comment by Wirednuke83** [comment]
More specifically... Players seem to gain skill from swings that have no effect. Including, but not limited to, Sparring the ghost in kesmai.

**Comment by zrikzlok** [comment]
this has been fixed on ghost now.. unsure on skellies

**Comment by Tawnos-LOK** [comment]
Retested - Not gaining skill on little damage anymore
