### ISSUE TITLE
Residual encumbrance

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#885]
Sometimes, if you are encumbered... your remain so even after unloading the gold until you log back out and back in agian. [Reported by Wirednuke]

**Comment by Leolus** [comment]
Issue it the same as https://github.com/jkachhad/Stormhalter/issues/872

**Comment by jkachhad** [comment]
Resolved on the next patch. Splitting gold and dropping to ground did not update weight. With the fixes, any successful item drop will cause a weight update.
