### ISSUE TITLE
Fight targets friendly entities

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#891]
If a player is flagged for you then the Fight command from that player can target you.

Example:
Apros is flagged as hostile to Leo
Leo and Apros on the same tile
Apros using Fight command or * to attack
Sometimes Leo becomes target of attack [Report by Leokn]

**Comment by stormhalter** [comment]
I flipped some code around to see if it avoids resolving player groups, let me know if you continue to have this issue. [Reported by Lux]

**Comment by Chilly021** [comment]
There is an issue with flagging still despite them not being pink in a party. This causes the Asterisk to hit a friendly. The user can proc or cast fireball in party, due to the flag doesn't happen in color fashion, the user sometimes ends up killing the other player.

**Comment by jkachhad** [comment]
I've determined this to be related to how hostility is calculated and attacker/defender damage history. Hostile determination has been refactored.  

`MobileEntity` 
- Determines hostility based on alignments.   

`CreatureEntity` : `MobileEntity`
- `VendorEntity` is not hostile.
- Idle `RescueAI` are not hostile.
- `Director` is not hostile if the `CreatureEntity` has `IsSubordinate` set to `true`
- Any attackers are hostile.

`PlayerEntity` : `MobileEntity`
- Aggressive players are hostile

After this change, `Fight`, `Kick`, `Throw`, `Shoot`, and `Jumpkick` all now only consider hostile targets.

Apros and Leo are on the same tile.
- If both issue an attack command, no attacks will occur.
- Apros attacks Leo using shift + double-click,  Leo now has a defensive flag and Apros is considered hostile.  Leo is still non-hostile to Apros.
- Apros issues fight using `*`, no attack will occur as Leo is not hostile.
- Leo issues fight using '*', attack will occur as there is a defensive flag, and Apros is a hostile.
- Apros issues fight using `*`, Leo is not a hostile, he is only defending himself.

- If Leo issues a `pet` command, hostility is forgiven and return initial state.

**Comment by Leolus** [comment]
The most common scenario involving the * key have been AoE spells. Especially with the proc weapons. If the * didn't target people who aren't flagged then that'll resolve that issue as well.

**Comment by jkachhad** [comment]
Could additionally add that members of a party are never considered hostile.

**Comment by Chilly021** [comment]
We need to test this, but I am going to close it. Can always re-open.
