### ISSUE TITLE
Copper Halberd has no Penetration Value

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#893]
SGA has veryheavy, as an example. [Report by Leokn]

**Comment by jkachhad** [comment]
I can't seem to find any documentation that the halberd has any penetration. It would make sense since you're attacking from a distance?

**Comment by trlook** [comment]
Penetration only affects shield spell so this doesn't really have much of an impact.

**Comment by sproatba** [comment]
Base halberd has penetration set so this hally inherits it, unless we need to adjust it for pvp or the be wielded by a mob for some reason this can be closed @Chilly021 @SewerCzar
