### ISSUE TITLE
Wands should be beltable

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#906]
Wands cannot be placed on a belt. Should be able to do this. [Report by Leokn]

**Comment by jkachhad** [comment]
`Wands` now inherit from `MeleeWeapon` -- all existing instances will be removed.
					- They deal a minimum of 1 damage and maximum of 2, unless otherwise overridden.
					- They deal piercing damage, unless otherwise overridden.
					- They can be both belted and placed in your backpack.
