### ISSUE TITLE
Disintegrate - black ceramic bottles

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#907]
Have the Disintegrate spell remove black ceramic bottles.  They clog up mob item slots, especially noticeable in Axe UD [Suggested by Vernak]

**Comment by yarrim** [comment]
Perhaps an intensity 2 Disintegrate, which targets more object types.

**Comment by Tawnos-LOK** [comment]
Hmm - that is an interesting suggestion @yarrim for granularity.  Right now, items just have the boolean flag for True / False so some additional effort would have to be made to revamp along those lines.  I like it, though

**Comment by Tawnos-LOK** [comment]
Closing my issue - going to reorganize suggestions around Disintegrate from various players.
