### ISSUE TITLE
Client becomes "disconnected" from chat

### ISSUE THREAD

**Issue by ghost** [jkachhad/Stormhalter#921]
I haven't been able to reproduce this reliably, but at times my client will stop sending chat messages. I have to exit to the conference and come back into the game to be able to talk again.

**Comment by jkachhad** [comment]
Is it after a long time of playing? The chat keeps an index of where to render the text from. It's possible it's getting out of the range. See if you can gather a replay, if it's reproducible in the replay, then we fix it.

**Comment by Tawnos-LOK** [comment]
Resolved in the bug fix concerning OnPlayerIncoming messages with the player name bugging the text log.
