### ISSUE TITLE
Recall Ring triggers rebind before removal

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#927]
If a recall ring is dropped into another ring slot instead of a bag then the recall occurs on spot instead of where the recall was set. Suspect the trigger for bind is before the trigger for teleport. [Report by Leokn]

**Comment by Leolus** [comment]
Additionally the recall should probably trigger the teleport before checking if you can bind a recall ring to the current location. Spots like trainers and door tiles aren't recallable from by dropping the ring into another ring slot because you can't set a ring there.

**Comment by Leolus** [comment]
Another observation, dropping a recall ring on another item on the tile bounces the ring back to your ring slot without recalling. This means a panic pull onto a tile you're looking at doesn't work. Reproduce this by dropping a ring on an item on the floor with the crossed circle icon on the tooltip.

**Comment by Leolus** [comment]
A command like "pull ring 4" would be awesome if implemented to pull recalls as well.

**Comment by jkachhad** [comment]
I've reverted the change previously, and a new implementation should fix the base issue from #877
