### ISSUE TITLE
Enchanting an untied weapons prevents it from being tied

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#929]
Attempted to enchant an OL staff on the ground on one character, second character then could not use the staff. Did not pick up the staff on first character [Report by Peetester]

**Comment by jkachhad** [comment]
You might consider using "props" on the staff. It should not be possible to bind with just Enchant Weapon as it only sets the enchanted flag. Would you consider posting the replay?

**Comment by Tawnos-LOK** [comment]
Not sure if this one got resolved.  Reworded, this was an issue with enchanting weapons before the have an owner established

**Comment by Chilly021** [comment]
@Leolus  any update on this one? Not sure if this is still a bug.

**Comment by jkachhad** [comment]
No issues identified. I was able to verify a sword has IsEnchanted to `False`  and Owner as `Null`.  After enchanting, the owner was still null. When lifting, the owner changed as expected. Marking as resolved.
