### ISSUE TITLE
Carfel difficulty/strength

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#933]
Carfel seems to be tuned way too weak.  On my thief at 18/7th Dan, i solo'd him and only took 10 damage.  He seems to be on par with Trog, being that once you even get remotely close to the endgame you've already far surpassed him.  I think he should be more formidable for sure. [Report by Xero]

**Comment by Tawnos-LOK** [comment]
Carfel was tuned up since this issue was opened.
