### ISSUE TITLE
Wizard Trainers

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#937]
My wizard just received the peek spell (somewhere around level 12 magic).  I can no longer train magic in kesmai or Oakvale because I've surpassed the trainers.  The magic trainers should probably all train up to around 14 for ice spear level, and then at that point funnel you toward the endgame trainers.  Seems like they're set a bit low. [Report by XeroX]

**Comment by dedmist** [comment]
Xero — Today at 2:05 PM
I just sent feedback thru the client concerning wizard trainers being too low level. I’m an idiot and this one was user error. Ignore that report please.
