### ISSUE TITLE
fire on water

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#95]
shouldn't be able to be cast on water. 

![image](https://user-images.githubusercontent.com/51264376/58752321-dcfdae00-847a-11e9-9f4b-3b23270a912b.png)

**Comment by jkachhad** [comment]
You are correct about this. But, is it something we should disable because it was a mechanic, or keep it to increase the variability in boss fights or combat.

**Comment by zrikzlok** [comment]
Could be an interesting mechanic if casting fire on water caused the tile to temporarily turn into dirt/steam, maybe blocking view?. Also if you cast ice storm on water it turns it into an ice tile.

**Comment by jkachhad** [comment]
This is now resolved as of v0.39 - Fire spells can no longer be placed over water.
