### ISSUE TITLE
2 Hexes of Darkness doesn't work correctly

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#952]
Players cannot see through 2 hexes of darkness - consistent with every other version of the game.  However, mobs with NV can.  This is creating situations where mobs you cannot see at all can hit you or cast on you from out of nowhere.  i.e. - getting hit with Concussion within 3x3 dark in Oak UD [Reported by Vernak]

**Comment by jkachhad** [comment]
I setup a test case for this, but could not replicate in the test that the entities saw each other past 2 hexes of darkness, even with NV. I setup in Oak UD and ran around for a bit. The only time the wizards casted concussion was when they were forced to cast, as no other AI was around to help them. In which case, they concussed themselves to death.

**Comment by Chilly021** [comment]
Is this still an issue? @Tawnos-LOK  / @jkachhad

**Comment by jkachhad** [comment]
![image](https://user-images.githubusercontent.com/1934897/155899555-bcdf123c-8db4-4896-a5ae-606b1049b2a8.png)
He could not see me when I moved once hex E.
