### ISSUE TITLE
Palliative Elemental staying on creature list

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#977]
Similarly to the previous bug about teleporters and jumping down air hexes, the Palliative Elementals in heart of the grove are lingering / ghosting on the combat list after they either die or complete their quest mission. [Reported by Vernak]

**Comment by Tawnos-LOK** [comment]
Retested.  Elementals do not seem to linger on the creature list any longer with the successful arrival at the Heart
