### ISSUE TITLE
npc pathing problem with blown walls

### ISSUE THREAD

**Issue by zrikzlok** [jkachhad/Stormhalter#98]
Seems to be some strange pathing around blown walls. If you're more than 2 hexes away from the blown wall (on the other side from an NPC) they don't attempt to run through the blown wall. 

--edit I think this may be an ORC problem only.

**Comment by jkachhad** [comment]
The AI is similar for all creatures, so they should all have the same issue. I tested on -1, and the orcs seem to walk into rubble when I walk into it, or through it to get to me if I'm opposite.

What prevents the AI from moving is the lack of a true "floor." While you may see a floor art, it could be just a "static" component. This might be occurring for walls that are not being properly marked as indestructible, in which case they don't really need a floor as you don't ever expect to walk on it.

Do you recall where this was occurring?

**Comment by zrikzlok** [comment]
I believe it was occurring near the stairs up to -3 (straight down from daisy lair area), in between the small section of walls. I assume they were probably supposed to be indestructible, but I was able to blow them away, however the AI may have seen them as indestructible.

**Comment by jkachhad** [comment]
Ok, we'll see if it still occurs with this next patch that fixes various walls.
