### ISSUE TITLE
Died after logout -- ghost on char select screen

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#990]
So, I was on my wizard in -300 with Logtoggle.  I casted WB on myself.  My daughter got home and I had to log out quickly, so I moved to his hex and logged out.  A while later in discord I got a ping that he had my staff and that i had somehow died, even though I was alive when I logged out.  When I got back to the computer and logged into the client, my character select icon was a ghost, not a wizard.  Logtoggle says he was getting disconnected when he tried to rezz me (we assume because I wasn't connected).  I logged back into the game as a ghost and I could chat with him, but he could not see me on the ground in his hex.  I released to town and returned to normal. [Report by XeroX]

**Comment by Chilly021** [comment]
I think we can re-open this if we have some steps of reproduction. No way to validate this if this is still occurring or not.
