### ISSUE TITLE
Lock Spell buttons

### ISSUE THREAD

**Issue by stormhalter** [jkachhad/Stormhalter#997]
Add ability to lock spell icons to the quick-cast bar, either via a lock/unlock button or Hotkey [Suggested by Kajoq]

**Comment by yarrim** [comment]
Solving the same problem as #782. Sometimes, a double-click-to-cast is interpreted as a drag and instead removes the spell from the hotbar.

**Comment by Tawnos-LOK** [comment]
Closing, with a note that #782 is still open.  Merging issues.
